server {
    listen 80;
    listen [::]:80;
    server_name ohar.name www.ohar.name;

    return 301 https://ohar.name$request_uri;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name 70.34.249.15 _;

    root /var/www/ohar.name/current;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name www.ohar.name;

    ssl_certificate /etc/letsencrypt/live/ohar.name/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ohar.name/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    if ($server_protocol != "HTTP/2.0") {
        return 426;
    }

    return 301 https://ohar.name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name ohar.name;
    root /var/www/ohar.name/current;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/ohar.name/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ohar.name/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    if ($server_protocol != "HTTP/2.0") {
        return 426;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|jpg|jpeg|gif|png|webp|svg|ico|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}
