const pageCopy = {
  ru: {
    title: 'Резюме',
    description: 'Резюме Павла Лысенко, Senior Frontend Developer',
    print: 'Печать в PDF',
    language: 'Язык резюме',
  },
  en: {
    title: 'CV',
    description: 'CV of Pavel Lysenko, Senior Frontend Developer',
    print: 'Print to PDF',
    language: 'CV language',
  },
}

const cvData = {
  ru: {
    name: 'Лысенко Павел',
    role: 'Senior Frontend Developer',
    salaryLabel: 'Ожидания по зарплате',
    salaries: ['от 320 к ₽ (ТК)', 'от 400 к ₽ (ИП)'],
    summaryLabel: 'О себе',
    summary: [
      'Senior Frontend Engineer с 14+ годами опыта. Делаю любой фронтенд.',
      'Разрабатывал высоконагруженные клиентские приложения для Яндекса, Wildberries и финтех-проектов.',
      'Специализируюсь на SPA-приложениях, сложной бизнес-логике, удобстве пользователей, производительности и визуализации данных.',
      'Проектировал антифрод-системы, разрабатывал браузерные расширения, разрабатывал API и интеграцию с OAuth, руководил разработкой небольших команд.',
    ],
    contactsTitle: 'Контакты',
    contacts: [
      { label: 'Email', href: 'mailto:job@ohar.name', value: 'job@ohar.name' },
      { label: 'Телефон', href: 'tel:+79852685323', value: '+7 (985) 268-53-23' },
      { label: 'GitHub', href: 'https://github.com/Ohar', value: 'github.com/Ohar', external: true },
    ],
    targetTitle: 'Желаемая должность',
    targetRole: 'Senior Frontend Developer',
    targetItems: [
      { label: 'Занятость', value: 'Полная, частичная, проектная работа' },
      { label: 'Формат', value: 'Офис / удаленка' },
      { label: 'Локация', value: 'Москва, Фили; ≤1,5 ч до офиса' },
    ],
    experienceTitle: 'Опыт работы — 14 лет 9 месяцев',
    experience: [
      {
        screenDate: 'Июнь 2024 — Июнь 2026',
        printDate: '2024-06 – 2026-06',
        duration: '2 года 1 месяц',
        title: 'Senior Frontend Developer',
        company: 'Вайлдберриз, Москва',
        companyUrl: 'https://wb.ru/',
        companyUrlText: 'wb.ru',
        description: [
          'Разработал ключевые интерфейсы внутренней платформы A/B-тестирования для 500+ аналитиков: настройку экспериментов и аналитические дашборды с визуализацией результатов тестов и статистических метрик. Разработал Chrome Extension для проверки экспериментальных сценариев на wildberries.ru с интеграцией через OAuth и API платформы.',
        ],
        stack: 'TypeScript, React, Redux, Zustand, Ant Design, Vite, Recharts, Figma.',
      },
      {
        screenDate: 'Июнь 2023 — Июнь 2024',
        printDate: '2023-06 – 2024-06',
        duration: '1 год 1 месяц',
        title: 'Senior UI Developer',
        company: 'Яндекс, Москва',
        companyUrl: 'https://ya.ru',
        companyUrlText: 'ya.ru',
        description: [
          'Разработка главной страницы ya.ru и yandex.kz: поиск, виджеты, реклама и интеграции с сервисами Яндекса. Миграция интерфейсов с BEM на React, оптимизация производительности для слабых устройств и старых браузеров.',
        ],
        stack: 'JavaScript, React, Vue.js, Svelte, BEM.',
      },
      {
        screenDate: 'Июнь 2022 — Апрель 2023',
        printDate: '2022-06 – 2023-04',
        duration: '11 месяцев',
        title: 'Frontend Tech Lead',
        company: 'ООО «ЭфЭнСи», Москва (контракт с ООО «Комус»)',
        description: [
          'Глобальный рефакторинг: перевёл устаревший внутренний и внешний порталы Комуса с jQuery на Vue, обновил архитектуру, уменьшил легаси-код и упростил интерфейсы.',
        ],
        stack: 'TypeScript, JavaScript, Vue.js, jQuery, LESS, Webpack, Hybris, Figma.',
      },
      {
        screenDate: 'Февраль 2020 — Январь 2022',
        printDate: '2020-02 – 2022-01',
        duration: '2 года',
        title: 'Frontend Team Lead',
        company: 'Кибертоника, Москва',
        companyUrl: 'https://cybertonica.com/',
        companyUrlText: 'cybertonica.com',
        description: [
          'Разработка антифрод-платформы для банков и платежных систем. Руководил фронтенд-направлением, развивал интерфейсы анализа транзакций и мониторинга риска в реальном времени. Переработал и расширил fingerprinting SDK для идентификации пользователей без авторизации, перевел внутренний скрипт в полноценный NPM-пакет.',
        ],
        stack: 'React, Redux, JavaScript, WebSocket.',
      },
    ],
    compactExperience: [
      {
        screenDate: 'Январь 2019 — Август 2019',
        printDate: '2019-01 – 2019-08',
        duration: '8 месяцев',
        title: 'Frontend Engineer',
        company: 'Сфера (банк БКС), Москва (закрыт)',
        description: ['Разработал модуль финансовой информации и основу системы торгов с интеграцией API.'],
        stack: 'JavaScript, React.js, LESS, Webpack.',
      },
      {
        screenDate: 'Июнь 2018 — Октябрь 2018',
        printDate: '2018-06 – 2018-10',
        duration: '5 месяцев',
        title: 'Frontend Lead Developer',
        company: 'SkillMill.io, Австрия (не запущен)',
        description: [
          'Удаленная работа. Разработал внутренний чат с пересылкой файлов на WebSockets и страницу профиля. Автоматизировал сборку Webpack и выкатку проекта shell-скриптами.',
        ],
        stack: 'JavaScript, Vue.js, LESS, HTML, Webpack, Bash, WebSocket.',
      },
      {
        screenDate: 'Ноябрь 2017 — Май 2018',
        printDate: '2017-11 – 2018-05',
        duration: '7 месяцев',
        title: 'Frontend Team Lead',
        company: 'Carrus Mobile, Inc, США (закрыт)',
        description: [
          'Разработал менеджерскую панель на React, отвечал за весь фронтенд, планировал архитектуру и создавал новый функционал. Автоматизировал сборку и выкатку, настроил Nginx для фронта, разделил сайт на независимые бандлы и сборки для разных окружений.',
        ],
        stack: 'JavaScript, SCSS, HTML, React.js, Redux, Webpack, Bash.',
      },
      {
        screenDate: 'Январь 2017 — Сентябрь 2017',
        printDate: '2017-01 – 2017-09',
        duration: '9 месяцев',
        title: 'Программист',
        company: 'YouDo, Россия',
        companyUrl: 'https://youdo.com/',
        companyUrlText: 'youdo.com',
        description: ['Разработка и поддержка фронта YouDo.com, перевод проекта на ES2015, внедрение React и Redux.'],
        stack: 'JavaScript, LESS, HTML, Angular.js, React.js, Lodash, Jest, Backbone.',
      },
      {
        screenDate: 'Июль 2015 — Январь 2017',
        printDate: '2015-07 – 2017-01',
        duration: '1 год 7 месяцев',
        title: 'Fullstack Developer / Product Owner',
        company: 'Kamagames Studio, Москва',
        companyUrl: 'https://kamagames.com/',
        companyUrlText: 'kamagames.com',
        description: [
          'Полностью отвечал за внутренний проект визуализации данных и построения отчетов: получал требования, разрабатывал фронт, бэк и API, интегрировал сторонние сервисы. Проводил технические собеседования. Разрабатывал API на NodeJS, подключал OAuth-авторизацию через LDAP, поддерживал проект на ReactJS.',
        ],
        stack: 'JavaScript, SCSS, HTML, Angular.js, React.js, Lodash, NodeJS, Mocha, Chai, WebSockets, MySQL, Redis.',
      },
    ],
    oldExperienceSummary: {
      title: 'Ранний опыт до 2016',
      text: 'Frontend-разработка в Localway, Workle, NullPointer, Оверсан и Artus.',
    },
    legacyExperience: [
      {
        screenDate: 'Декабрь 2014 — Июль 2015',
        printDate: '2014-12 – 2015-07',
        duration: '8 месяцев',
        title: 'Фронт-разработчик',
        company: 'Localway.ru, Москва (закрыт)',
        description: [
          'Поддержка сервиса на AngularJS: исправление багов, верстка, разработка новых страниц, блоков, директив, в том числе для мобильной версии и админки.',
        ],
        stack: 'JavaScript, jQuery, LESS, CSS, HTML, AngularJS, Underscore.js, Python.',
      },
      {
        screenDate: 'Июнь 2014 — Ноябрь 2014',
        printDate: '2014-06 – 2014-11',
        duration: '6 месяцев',
        title: 'Фронт-разработчик',
        company: 'Workle.ru, Москва',
        companyUrl: 'https://www.workle.ru/',
        companyUrlText: 'workle.ru',
        description: ['Переделал страницы спецпредложений и поиска туров, сделал несколько страниц в админке.'],
        stack: 'JavaScript, jQuery, CSS, БЭМ, Backbone.js, Require.js.',
      },
      {
        screenDate: 'Ноябрь 2013 — Май 2014',
        printDate: '2013-11 – 2014-05',
        duration: '7 месяцев',
        title: 'JavaScript-разработчик',
        company: 'NullPointer, Москва',
        companyUrl: 'https://null-pointer.ru/',
        companyUrlText: 'null-pointer.ru',
        description: ['Модули на AngularJS, поиск по базе с сортировкой и псевдопостраничной выдачей.'],
        stack: 'JavaScript, CSS, AngularJS, Require.js, Underscore.js.',
      },
      {
        screenDate: 'Апрель 2012 — Ноябрь 2013',
        printDate: '2012-04 – 2013-11',
        duration: '1 год 8 месяцев',
        title: 'Оверсан',
        company: 'Москва (закрыт)',
        roles: [
          {
            title: 'Разработчик интерфейсов',
            screenDate: 'Июль 2012 — Ноябрь 2013',
            printDate: '2012-07 – 2013-11',
            description: ['Разработал интерфейс панели управления услугами, UX и UI сайтов и проектов компании. Сделал несколько сайтов дочерних проектов.'],
            stack: 'CSS, JavaScript, jQuery, Razor.',
          },
          {
            title: 'Верстальщик',
            screenDate: 'Апрель 2012 — Июль 2012',
            printDate: '2012-04 – 2012-07',
            description: ['Сделал главный сайт компании: верстка, шаблоны, скрипты, доработка сторонних JS-библиотек.'],
            stack: 'CSS, JavaScript, jQuery.',
          },
        ],
      },
      {
        screenDate: 'Июнь 2010 — Декабрь 2011',
        printDate: '2010-06 – 2011-12',
        duration: '1 год 7 месяцев',
        title: 'Контент-менеджер',
        company: 'Интернет-агентство «Артус», Москва',
        companyUrl: 'https://www.artus.ru/',
        companyUrlText: 'www.artus.ru',
        description: [
          'Наполнил контентом, вычитал и оттипографировал десятки сайтов. Получил сертификат Битрикс. Делал анкеты, баннеры, настраивал страницы, дополнил должностную инструкцию и стандарты работы.',
        ],
        stack: 'CSS, HTML.',
      },
    ],
    educationTitle: 'Образование и курсы',
    education: [
      {
        title: '2012 — Неоконченное высшее',
        text: 'Национальный исследовательский университет «Высшая школа экономики», Москва. Вычислительные комплексы, машины и сети, два курса.',
      },
      {
        title: '2011 — JavaScript',
        text: '«JavaScript. Основы веб-программирования», Учебный центр «Специалист» при МГТУ им. Н. Э. Баумана.',
      },
      {
        title: '2011 — HTML и CSS',
        text: '«HTML, CSS, кроссбраузерная верстка, основы юзабилити», Учебный центр «Специалист».',
      },
      {
        title: '2010 — 1С-Битрикс',
        text: 'Сертификация «Администрирование системы “Битрикс”».',
      },
    ],
    skillsTitle: 'Навыки',
    skills: [
      'JavaScript',
      'TypeScript',
      'React',
      'Vue.js',
      'Svelte',
      'Node.js',
      'Webpack',
      'Vite',
      'Jest',
      'UX',
      'Usability',
      'БЭМ',
      'SPA',
      'SSR',
      'WebSocket',
      'Browser Extensions',
      'Technical Leadership',
      'Electron',
      'Redis',
      'Agile',
      'OAuth',
      'Performance Optimization',
    ],
    additionalTitle: 'Дополнительно',
    additional: [
      {
        title: 'Языки',
        lines: ['Русский — родной.', 'Английский — B2.', 'Французский — A1.'],
      },
    ],
    projectsTitle: 'Ключевые проекты',
    projects: [
      'Антифрод-платформа Кибертоники',
      'Browser Fingerprinting SDK для Кибертоники',
      'Платформа A/B-тестирования Wildberries',
      'Главная страница Яндекса',
    ],
  },
  en: {
    name: 'Pavel Lysenko',
    role: 'Senior Frontend Developer / React / TypeScript',
    salaryLabel: 'Salary expectations',
    salaries: ['$4,500 net'],
    summaryLabel: 'About me',
    summary: [
      'Senior Frontend Engineer with 14+ years of experience in JavaScript, TypeScript, React, and Vue.js.',
      'I build complex web interfaces, internal platforms, dashboards, browser extensions, and data visualization tools.',
      'I have worked on products for Yandex, Wildberries, fintech companies, and international startups.',
      'My focus areas are SPA architecture, performance optimization, complex business logic, API/OAuth integrations, and maintainable frontend systems.',
    ],
    contactsTitle: 'Contacts',
    contacts: [
      { label: 'Email', href: 'mailto:job@ohar.name', value: 'job@ohar.name' },
      { label: 'Phone', href: 'tel:+79852685323', value: '+7 (985) 268-53-23' },
      { label: 'GitHub', href: 'https://github.com/Ohar', value: 'github.com/Ohar', external: true },
    ],
    targetTitle: 'Desired position',
    targetRole: 'Senior Frontend Developer / React / TypeScript',
    targetItems: [
      { label: 'Employment', value: 'Full time, part time, project work' },
      { label: 'Format', value: 'Office, remote, hybrid, rotation, traveling' },
      { label: 'Location', value: 'Moscow, Filyovskiy Park; ready to relocate' },
    ],
    experienceTitle: 'Work experience - 15 years 2 months',
    experience: [
      {
        screenDate: 'June 2024 - till now',
        printDate: '2024-06 - now',
        duration: '2 years 1 month',
        title: 'Senior Frontend Developer',
        company: 'Wildberries, Moscow',
        companyUrl: 'https://career.wb.ru/',
        companyUrlText: 'career.wb.ru',
        description: [
          'Developed key interfaces for an internal A/B testing platform used by 500+ analysts: experiment setup flows, analytical dashboards, test result visualization, and statistical metrics. Built a Chrome Extension for validating experimental scenarios on wildberries.ru, integrated with the platform through OAuth and internal APIs.',
        ],
        stack: 'TypeScript, React, Redux, Zustand, Ant Design, Vite, Recharts, Figma.',
      },
      {
        screenDate: 'June 2023 - June 2024',
        printDate: '2023-06 - 2024-06',
        duration: '1 year 1 month',
        title: 'UI Developer',
        company: 'Yandex, Moscow',
        companyUrl: 'https://yandex.ru/jobs/',
        companyUrlText: 'yandex.ru/jobs',
        description: [
          'Worked on the main pages of ya.ru and yandex.kz: search, widgets, advertising modules, and integrations with Yandex services. Participated in migrating interfaces from BEM to React and improving performance for low-end devices and legacy browsers.',
        ],
        stack: 'JavaScript, React, Vue.js, Svelte, BEM.',
      },
      {
        screenDate: 'January 2022 - April 2023',
        printDate: '2022-01 - 2023-04',
        duration: '1 year 4 months',
        title: 'Frontend Tech Lead',
        company: 'FNC, contract with Komus',
        description: [
          'Migrated legacy internal and external Komus portals from jQuery to Vue.js within a Hybris-based enterprise system. Refactored outdated frontend code and improved maintainability of existing interfaces.',
        ],
        stack: 'TypeScript, JavaScript, Vue.js, jQuery, LESS, Webpack, Hybris, Figma.',
      },
      {
        screenDate: 'January 2020 - January 2022',
        printDate: '2020-01 - 2022-01',
        duration: '2 years 1 month',
        title: 'Frontend Team Lead',
        company: 'Cybertonica Ltd, Moscow',
        companyUrl: 'https://cybertonica.com/',
        companyUrlText: 'cybertonica.com',
        description: [
          'Led the frontend direction for an antifraud platform used by banks and payment systems. Developed a React-based management panel and frontend architecture for a web platform. Configured Webpack builds for different environments and automated frontend deployment.',
        ],
        stack: 'JavaScript, React, Redux, SCSS, HTML, Webpack, Bash.',
      },
    ],
    compactExperience: [
      {
        screenDate: 'January 2019 - August 2019',
        printDate: '2019-01 - 2019-08',
        duration: '8 months',
        title: 'Frontend Engineer',
        company: 'Sfera.ru, Moscow',
        companyUrl: 'https://sfera.ru/',
        companyUrlText: 'sfera.ru',
        description: [
          'Developed financial information modules for income, expenses, debts, and related user data. Built core frontend parts of a trading system with third-party API integration.',
        ],
        stack: 'JavaScript, React, LESS, Webpack, Git, GitLab.',
      },
      {
        screenDate: 'June 2018 - October 2018',
        printDate: '2018-06 - 2018-10',
        duration: '5 months',
        title: 'Frontend Lead Developer',
        company: 'Skillmill',
        description: [
          'Developed an internal chat system with WebSocket-based messaging, file uploads, and user profile pages. Automated release and deployment scripts.',
        ],
        stack: 'JavaScript, Vue.js, WebSocket, HTML, LESS, Webpack, Bash.',
      },
      {
        screenDate: 'November 2017 - May 2018',
        printDate: '2017-11 - 2018-05',
        duration: '7 months',
        title: 'Frontend Team Lead',
        company: 'Carrus Mobile, Inc',
        companyUrl: 'https://breakerlog.com/',
        companyUrlText: 'breakerlog.com',
        description: [
          'Developed a React-based management panel and frontend architecture for a web platform. Configured Webpack builds for different environments and automated frontend deployment.',
        ],
        stack: 'JavaScript, React, Redux, SCSS, HTML, Webpack, Bash.',
      },
      {
        screenDate: 'January 2017 - September 2017',
        printDate: '2017-01 - 2017-09',
        duration: '9 months',
        title: 'Programmer',
        company: 'YouDo, Russia',
        companyUrl: 'https://youdo.com/',
        companyUrlText: 'youdo.com',
        description: [
          'Maintained YouDo.com frontend, migrated parts of the codebase to ES2015/Babel, and integrated React/Redux into legacy frontend architecture.',
        ],
        stack: 'JavaScript, AngularJS, React, Redux, Backbone, Jest, LESS.',
      },
      {
        screenDate: 'July 2015 - January 2017',
        printDate: '2015-07 - 2017-01',
        duration: '1 year 7 months',
        title: 'Fullstack Developer / Product Owner',
        company: 'KamaGames Studio, Moscow',
        companyUrl: 'https://kamagames.com/',
        companyUrlText: 'kamagames.com',
        description: [
          'Owned an internal reporting and data visualization service used by internal teams. Gathered requirements, developed the frontend with AngularJS, built Node.js API endpoints, integrated third-party services, and coordinated data collection across departments. Participated in frontend and fullstack developer interviews.',
        ],
        stack: 'JavaScript, AngularJS, React, Node.js, SCSS, HTML, Lodash, Mocha, Chai, WebSocket, MySQL, Redis, OAuth.',
      },
    ],
    oldExperienceSummary: {
      title: 'Earlier experience before 2016',
      text: 'Frontend development at Localway, Workle, NullPointer, Oversun, and Artus.',
    },
    legacyExperience: [
      {
        screenDate: 'December 2014 - July 2015',
        printDate: '2014-12 - 2015-07',
        duration: '8 months',
        title: 'Frontend Developer',
        company: 'Localway.ru, Moscow',
        companyUrl: 'https://localway.ru/',
        companyUrlText: 'localway.ru',
        description: [
          'Maintained and developed Localway.ru frontend with AngularJS. Implemented new pages, modules, directives, layouts, and admin panel features for the main and mobile versions of the site.',
        ],
        stack: 'JavaScript, AngularJS, jQuery, HTML, CSS, Underscore.js, Python.',
      },
      {
        screenDate: 'June 2014 - November 2014',
        printDate: '2014-06 - 2014-11',
        duration: '6 months',
        title: 'Frontend Developer',
        company: 'Workle, Moscow',
        companyUrl: 'https://www.workle.ru/t/hh',
        companyUrlText: 'workle.ru',
        description: [
          'Developed and maintained frontend features, layouts, special offer pages, tour search flows, and admin panel pages.',
        ],
        stack: 'JavaScript, jQuery, HTML, CSS, BEM, Backbone.js, RequireJS.',
      },
      {
        screenDate: 'November 2013 - May 2014',
        printDate: '2013-11 - 2014-05',
        duration: '7 months',
        title: 'JavaScript Developer',
        company: 'NullPointer, Moscow',
        companyUrl: 'https://null-pointer.ru/',
        companyUrlText: 'null-pointer.ru',
        description: ['Developed AngularJS modules for database search, sorting, and pseudo-page pagination.'],
        stack: 'JavaScript, AngularJS, HTML, CSS, RequireJS, Underscore.js.',
      },
      {
        screenDate: 'April 2012 - November 2013',
        printDate: '2012-04 - 2013-11',
        duration: '1 year 8 months',
        title: 'Oversun',
        company: 'Moscow',
        companyUrl: 'https://www.oversun.ru/',
        companyUrlText: 'oversun.ru',
        roles: [
          {
            title: 'UI Developer',
            screenDate: 'July 2012 - November 2013',
            printDate: '2012-07 - 2013-11',
            description: [
              'Developed UI for the company\'s internal service panel and improved UX/UI for company websites and related projects. Built and maintained landing pages and child project websites.',
            ],
            stack: 'HTML, CSS, JavaScript, jQuery, Razor.',
          },
          {
            title: 'Web Coder',
            screenDate: 'April 2012 - July 2012',
            printDate: '2012-04 - 2012-07',
            description: [
              'Maintained the company website: layouts, templates, scripts, and frontend adjustments for third-party libraries.',
            ],
            stack: 'HTML, CSS, JavaScript, jQuery.',
          },
        ],
      },
      {
        screenDate: 'June 2010 - December 2011',
        printDate: '2010-06 - 2011-12',
        duration: '1 year 7 months',
        title: 'Content Manager',
        company: 'ARTUS Internet Agency, Moscow',
        companyUrl: 'https://www.artus.ru/',
        companyUrlText: 'www.artus.ru',
        description: [
          'Managed and updated content for multiple client websites. Created and configured forms, banners, and landing pages, proofread website content, and improved internal content management guidelines.',
        ],
        stack: 'HTML, CSS.',
      },
    ],
    educationTitle: 'Education and courses',
    education: [
      {
        title: '2012 - Incomplete higher education',
        text: 'National Research University Higher School of Economics, Moscow. Computing systems, machines and networks, quit after 2nd year.',
      },
      {
        title: '2011 - JavaScript',
        text: 'JavaScript. Fundamentals of Web programming, Training Center Specialist at the MSTU Bauman.',
      },
      {
        title: '2011 - HTML and CSS',
        text: 'HTML, CSS, cross-browser layout, UI basics, Training Center Specialist at the MSTU Bauman.',
      },
      {
        title: '2010 - 1C-Bitrix',
        text: 'System administration certification for Bitrix.',
      },
    ],
    skillsTitle: 'Skills',
    skills: [
      'JavaScript',
      'TypeScript',
      'React',
      'Redux',
      'Vue3',
      'Svelte',
      'Node.js',
      'Webpack',
      'Vite',
      'Jest',
      'UX',
      'Usability',
      'BEM',
      'SPA',
      'SSR',
      'WebSocket',
      'Browser Extensions',
      'OAuth',
      'Zustand',
      'Recharts',
      'Ant Design',
      'Performance Optimization',
    ],
    additionalTitle: 'Additional information',
    additional: [
      {
        title: 'Languages',
        lines: ['Russian - Native.', 'English - B2, Upper Intermediate.'],
      },
    ],
    projectsTitle: 'Key projects',
    projects: [
      'Cybertonica antifraud platform',
      'Browser Fingerprinting SDK',
      'Wildberries A/B testing platform',
      'Yandex main page',
    ],
  },
}

export { cvData, pageCopy }
