const siteCopy = {
  en: {
    languageSwitcher: {
      label: "Language",
      en: "English",
      ru: "Russian",
    },
    menu: {
      home: "Home",
      homeTitle: "Home",
      githubTitle: "GitHub profile",
      cv: "CV",
      cvTitle: "CV",
      portfolio: "Portfolio",
      portfolioTitle: "Portfolio",
      quotes: "Quotes",
      quotesTitle: "Quotes",
      contacts: "Contacts",
      contactsTitle: "Contact me",
      articles: "Articles",
      articlesTitle: "Articles",
      russianOnly: "in Russian",
    },
    home: {
      heading: "Pavel Lysenko",
      description: "Personal website of Pavel Lysenko, Lead Frontend Developer",
      keywords: ["Pavel Lysenko", "Lead Frontend Developer", "Ohar"],
    },
    contacts: {
      title: "Contacts",
      description: "How to contact Pavel Lysenko",
      keywords: ["Pavel Lysenko contacts", "Ohar contacts"],
      intro: "Hi, I'm Pavel Lysenko, a frontend engineer.",
      cvLink: "Download my CV",
      profilesTitle: "Elsewhere online",
    },
    portfolio: {
      title: "Portfolio",
      description: "Projects and work by Pavel Lysenko",
      keywords: ["Pavel Lysenko portfolio", "Ohar Studio"],
      heading: "Projects and applications",
      lead: "A separate showcase of my side projects is available at",
    },
    notFound: {
      title: "404: Not found",
      description: "The requested page could not be found",
      heading: "This page does not exist",
      fallback: "Here is a cat instead",
      imageAlt: "Cat",
    },
    tc: {
      title: "Trench Crusade",
      description: "Heretic Legion operatives for Trench Crusade",
      heading: "Trench Crusade: Heretic Legion",
      movement: "Move",
      ranged: "Ranged",
      melee: "Melee",
      armour: "Armour",
      base: "Base",
      baseUnit: "mm",
      equipment: "Equipment",
      abilities: "Abilities",
      none: "None.",
      keywords: "Keywords",
    },
  },
  ru: {
    languageSwitcher: {
      label: "Язык",
      en: "Английский",
      ru: "Русский",
    },
    menu: {
      home: "Главная",
      homeTitle: "На главную",
      githubTitle: "Профиль на GitHub",
      cv: "Резюме",
      cvTitle: "Резюме",
      portfolio: "Портфолио",
      portfolioTitle: "Портфолио",
      quotes: "Цитаты",
      quotesTitle: "Всякие цитаты",
      contacts: "Контакты",
      contactsTitle: "Связаться со мной",
      articles: "Статьи",
      articlesTitle: "Статьи обо всяком",
      russianOnly: "",
    },
    home: {
      heading: "Сайт Павла Лысенко",
      description: "Личный сайт Павла Лысенко, Lead Frontend Developer",
      keywords: ["Павел Лысенко", "Lead Frontend Developer", "Ohar"],
    },
    contacts: {
      title: "Контакты",
      description: "Как связаться с Павлом Лысенко",
      keywords: ["Контакты Павла Лысенко", "Ohar"],
      intro: "Привет! Меня зовут Павел Лысенко. Я веб-разработчик.",
      cvLink: "Скачать резюме",
      profilesTitle: "Другие сайты со мной",
    },
    portfolio: {
      title: "Портфолио",
      description: "Проекты и рабочие материалы Павла Лысенко",
      keywords: ["Портфолио Павла Лысенко", "Ohar Studio"],
      heading: "Портфолио приложений",
      lead: "Отдельная витрина пет-проектов находится на",
    },
    notFound: {
      title: "404: Не найдено",
      description: "Запрошенная страница не найдена",
      heading: "Такой страницы нет",
      fallback: "Зато есть котик",
      imageAlt: "Котик",
    },
    tc: {
      title: "Trench Crusade",
      description: "Легион еретиков для Trench Crusade",
      heading: "Trench Crusade: Легион еретиков",
      movement: "Движение",
      ranged: "Стрельба",
      melee: "Рукопашка",
      armour: "Броня",
      base: "Подставка",
      baseUnit: "мм",
      equipment: "Снаряжение",
      abilities: "Способности",
      none: "Нет.",
      keywords: "Ключи",
    },
  },
}

export default siteCopy
