export default [
  {
    id: 'krasota',
    probabilityWeight: 1,
    description: 'красота',
    aligmentId: 'any',
  },
  {
    id: 'blagotvoritelnost',
    probabilityWeight: 1,
    description: 'благотворительность',
    aligmentId: 'any_good',
  },
  {
    id: 'vysshee blago',
    probabilityWeight: 1,
    description: 'высшее благо',
    aligmentId: 'any_good',
  },
  {
    id: 'zhizn',
    probabilityWeight: 1,
    description: 'жизнь',
    aligmentId: 'any_good',
  },
  {
    id: 'uvazhenie',
    probabilityWeight: 1,
    description: 'уважение',
    aligmentId: 'any_good',
  },
  {
    id: 'samopozhertvovanie',
    probabilityWeight: 1,
    description: 'самопожертвование',
    aligmentId: 'any_good',
  },
  {
    id: 'dominirovanie',
    probabilityWeight: 1,
    description: 'доминирование',
    aligmentId: 'any_evil',
  },
  {
    id: 'zhadnost',
    probabilityWeight: 1,
    description: 'жадность',
    aligmentId: 'any_evil',
  },
  {
    id: 'moshch',
    probabilityWeight: 1,
    description: 'мощь',
    aligmentId: 'any_evil',
  },
  {
    id: 'bol',
    probabilityWeight: 1,
    description: 'боль',
    aligmentId: 'any_evil',
  },
  {
    id: 'kara',
    probabilityWeight: 1,
    description: 'кара',
    aligmentId: 'any_evil',
  },
  {
    id: 'reznia',
    probabilityWeight: 1,
    description: 'резня',
    aligmentId: 'any_evil',
  },
  {
    id: 'peremeny',
    probabilityWeight: 1,
    description: 'перемены',
    aligmentId: 'any_chaotic',
  },
  {
    id: 'nahodchivost',
    probabilityWeight: 1,
    description: 'находчивость',
    aligmentId: 'any_chaotic',
  },
  {
    id: 'svoboda',
    probabilityWeight: 1,
    description: 'свобода',
    aligmentId: 'any_chaotic',
  },
  {
    id: 'nezavisimost',
    probabilityWeight: 1,
    description: 'независимость',
    aligmentId: 'any_chaotic',
  },
  {
    id: 'otsutstvie_ogranichenii',
    probabilityWeight: 1,
    description: 'отсутствие ограничений',
    aligmentId: 'any_chaotic',
  },
  {
    id: 'kaprizy',
    probabilityWeight: 1,
    description: 'капризы',
    aligmentId: 'any_chaotic',
  },
  {
    id: 'obshchestvo',
    probabilityWeight: 1,
    description: 'общество',
    aligmentId: 'any_lawful',
  },
  {
    id: 'chestnost',
    probabilityWeight: 1,
    description: 'честность',
    aligmentId: 'any_lawful',
  },
  {
    id: 'chest',
    probabilityWeight: 1,
    description: 'честь',
    aligmentId: 'any_lawful',
  },
  {
    id: 'logika',
    probabilityWeight: 1,
    description: 'логика',
    aligmentId: 'any_lawful',
  },
  {
    id: 'otvetstvennost',
    probabilityWeight: 1,
    description: 'ответственность',
    aligmentId: 'any_lawful',
  },
  {
    id: 'traditcii',
    probabilityWeight: 1,
    description: 'традиции',
    aligmentId: 'any_lawful',
  },
  {
    id: 'ravnovesie',
    probabilityWeight: 1,
    description: 'равновесие',
    aligmentId: 'any_neutral',
  },
  {
    id: 'znanie',
    probabilityWeight: 1,
    description: 'знание',
    aligmentId: 'any_neutral',
  },
  {
    id: 'sam_zhivi_i_drugim_ne_meshai',
    probabilityWeight: 1,
    description: 'сам живи и другим не мешай',
    aligmentId: 'any_neutral',
  },
  {
    id: 'umerennost',
    probabilityWeight: 1,
    description: 'умеренность',
    aligmentId: 'any_neutral',
  },
  {
    id: 'neitralnost',
    probabilityWeight: 1,
    description: 'нейтральность',
    aligmentId: 'n',
  },
  {
    id: 'narod',
    probabilityWeight: 1,
    description: 'народ',
    aligmentId: 'not_evil',
  },
  {
    id: 'stremlenie',
    probabilityWeight: 1,
    description: 'стремление',
    aligmentId: 'any',
  },
  {
    id: 'issledovaniia',
    probabilityWeight: 1,
    description: 'исследования',
    aligmentId: 'any_neutral',
  },
  {
    id: 'slava',
    probabilityWeight: 1,
    description: 'слава',
    aligmentId: 'any',
  },
  {
    id: 'derzhava',
    probabilityWeight: 1,
    description: 'держава',
    aligmentId: 'any_lawful',
  },
  {
    id: 'iskuplenie',
    probabilityWeight: 1,
    description: 'искупление',
    aligmentId: 'not_neutral',
  },
  {
    id: 'samopoznanie',
    probabilityWeight: 1,
    description: 'самопознание',
    aligmentId: 'any',
  },
]
