export default [
  {
    id: 'sings-softly',
    probabilityWeight: 4,
    description: 'Склонен тихо петь',
    shouldAbleToSpeak: true,
  },
  {
    id: 'whistle-softly',
    probabilityWeight: 4,
    description: 'Склонен тихо насвистывать',
    shouldAbleToSpeak: true,
  },
  {
    id: 'moo-softly',
    probabilityWeight: 4,
    description: 'Склонен что-то тихо мычать',
    shouldAbleToSpeak: false,
  },
  {
    id: 'speaks-rhymes',
    probabilityWeight: 6,
    description: 'Говорит рифмами',
    shouldAbleToSpeak: true,
  },
  {
    id: 'speaks-fancifully',
    probabilityWeight: 6,
    description: 'Говорит причудливо',
    shouldAbleToSpeak: true,
  },
  {
    id: 'quiet-voice',
    probabilityWeight: 6,
    description: 'Тихий голос',
    shouldAbleToSpeak: true,
  },
  {
    id: 'loud-voice',
    probabilityWeight: 6,
    description: 'Громкий голос',
    shouldAbleToSpeak: true,
  },
  {
    id: 'swallows-words',
    probabilityWeight: 4,
    description: 'Проглатывает слова',
    shouldAbleToSpeak: true,
  },
  {
    id: 'lisps',
    probabilityWeight: 4,
    description: 'Шепелявит',
    shouldAbleToSpeak: true,
  },
  {
    id: 'stutters',
    probabilityWeight: 4,
    description: 'Заикается',
    shouldAbleToSpeak: true,
  },
  {
    id: 'speaks-too-clearly',
    probabilityWeight: 12,
    description: 'Чрезвычайно чётко проговаривает слова',
    shouldAbleToSpeak: true,
  },
  {
    id: 'speaks-too-loudly',
    probabilityWeight: 12,
    description: 'Говорит очень громко',
    shouldAbleToSpeak: true,
  },
  {
    id: 'whisper',
    probabilityWeight: 12,
    description: 'Шепчет',
    shouldAbleToSpeak: true,
  },
  {
    id: 'pompous-talk',
    probabilityWeight: 6,
    description: 'Использует помпезную речь',
    shouldAbleToSpeak: true,
  },
  {
    id: 'long-words',
    probabilityWeight: 6,
    description: 'Использует длинные слова',
    shouldAbleToSpeak: true,
  },
  {
    id: 'wrong-words',
    probabilityWeight: 12,
    description: 'Часто использует неправильные слова',
    shouldAbleToSpeak: true,
  },
  {
    id: 'swears',
    probabilityWeight: 6,
    description: 'Часто клянётся',
    shouldAbleToSpeak: true,
  },
  {
    id: 'pretentious',
    probabilityWeight: 6,
    description: 'Часто произносит пафосные фразы',
    shouldAbleToSpeak: true,
  },
  {
    id: 'jokes',
    probabilityWeight: 6,
    description: 'Постоянно шутит',
    shouldAbleToSpeak: true,
  },
  {
    id: 'puns',
    probabilityWeight: 6,
    description: 'Постоянно каламбурит',
    shouldAbleToSpeak: true,
  },
  {
    id: 'predicts-failures',
    probabilityWeight: 12,
    description: 'Часто предрекает неудачи',
    shouldAbleToSpeak: true,
  },
  {
    id: 'twitches',
    probabilityWeight: 12,
    description: 'Нервно дёргается',
    shouldAbleToSpeak: false,
  },
  {
    id: 'color-switch',
    probabilityWeight: 12,
    description: 'Иногда меняет цвет',
    shouldAbleToSpeak: false,
  },
  {
    id: 'pupsik',
    probabilityWeight: 1,
    description: 'Зовёт владельца только «Пупсик», но не замечает этого',
    shouldAbleToSpeak: true,
  },
  {
    id: 'jemanno',
    probabilityWeight: 12,
    description: 'Жеманно говорит',
    shouldAbleToSpeak: true,
  },
  {
    id: 'vejliv',
    probabilityWeight: 12,
    description: 'Чрезвычайно вежлив',
    shouldAbleToSpeak: true,
  },
  {
    id: 'skripit',
    probabilityWeight: 12,
    description: 'Поскрипывает при использовании',
    shouldAbleToSpeak: false,
  },
]
