export default {
  cost: 'Цена',
  weight: 'Масса',
  source: 'Источник информации',
  category: 'Категория',
  subcategory: 'Подкатегория',
  name: 'Название',
  description: 'Описание',
  damage: 'Урон',
  poisonType: 'Тип яда',
  saveThrow: 'Спасбросок',
  damageType: 'Тип урона',
  range: 'Дальность',
  blockHiding: 'Мешает скрытности',
  acChangeTo: 'КД',
  isTwoHanded: 'Двуручное',
  isReach: 'Досягаемость',
  isHeavy: 'Тяжёлое',
  isReloading: 'Перезарядка',
  needAmmo: 'Боеприпас',
}
