export default {
  acBonus: 'Бонус к КД',
  acChangeTo: 'КД',
  blockHiding: 'Мешает скрытности',
  category: 'Категория',
  cost: 'Цена',
  damage: 'Урон',
  damageType: 'Тип урона',
  description: 'Описание',
  isFinesse: 'Фехтовальное',
  isHeavy: 'Тяжёлое',
  isLight: 'Лёгкое',
  isReach: 'Досягаемость',
  isReloading: 'Перезарядка',
  isSpecial: 'Особое',
  isThrown: 'Метательное',
  isTwoHanded: 'Двуручное',
  name: 'Название',
  needAmmo: 'Боеприпас',
  poisonType: 'Тип яда',
  range: 'Дальность',
  requirementList: 'Требования',
  saveThrow: 'Спасбросок',
  source: 'Источник информации',
  subcategory: 'Подкатегория',
  weight: 'Масса',
}
