import listToCollectionById from '@/utils/listToCollectionById'

const dndAligmentList = [
  {
    id: 'no',
    oppositeId: null,
    name: {
        nominative: 'без мировоззрения',
        genitive: 'без мировоззрения',
        dative: 'без мировоззрения',
        accusative: 'без мировоззрения',
        instrumental: 'без мировоззрения',
        prepositional: 'без мировоззрения',
    },
  },
  {
    id: 'any',
    oppositeId: null,
    name: {
        nominative: 'любое',
        genitive: 'любого',
        dative: 'любому',
        accusative: 'любое',
        instrumental: 'любым',
        prepositional: 'любом',
    },
  },
  {
    id: 'any_good',
    oppositeId: 'any_evil',
    name: {
        nominative: 'любое доброе',
        genitive: 'любого доброго',
        dative: 'любому доброму',
        accusative: 'любое доброе',
        instrumental: 'любым добрым',
        prepositional: 'любом добром',
    },
  },
  {
    id: 'any_evil',
    oppositeId: 'any_good',
    name: {
        nominative: 'любое злое',
        genitive: 'любого злого',
        dative: 'любому злому',
        accusative: 'любое злое',
        instrumental: 'любым злым',
        prepositional: 'любом злом',
    },
  },
  {
    id: 'any_lawful',
    oppositeId: 'any_chaotic',
    name: {
        nominative: 'любое законопослушное',
        genitive: 'любого законопослушного',
        dative: 'любому законопослушному',
        accusative: 'любое законопослушное',
        instrumental: 'любым законопослушным',
        prepositional: 'любом законопослушном',
    },
  },
  {
    id: 'any_chaotic',
    oppositeId: 'any_lawful',
    name: {
        nominative: 'любое хаотичное',
        genitive: 'любого хаотичного',
        dative: 'любому хаотичному',
        accusative: 'любое хаотичное',
        instrumental: 'любым хаотичным',
        prepositional: 'любом хаотичном',
    },
  },
  {
    id: 'not_neutral',
    oppositeId: 'any_neutral',
    name: {
      nominative: 'не нейтральное',
      genitive: 'не нейтрального',
      dative: 'не нейтральному',
      accusative: 'не нейтральное',
      instrumental: 'не нейтральным',
      prepositional: 'не нейтральном',
    },
  },
  {
    id: 'not_good',
    oppositeId: 'not_evil',
    name: {
        nominative: 'недоброе',
        genitive: 'недоброго',
        dative: 'недоброму',
        accusative: 'недоброе',
        instrumental: 'недобрым',
        prepositional: 'недобром',
    },
  },
  {
    id: 'not_evil',
    oppositeId: 'not_good',
    name: {
        nominative: 'незлое',
        genitive: 'незлого',
        dative: 'незлому',
        accusative: 'незлое',
        instrumental: 'незлым',
        prepositional: 'незлом',
    },
  },
  {
    id: 'not_lawful',
    oppositeId: 'not_chaotic',
    name: {
        nominative: 'незаконопослушное',
        genitive: 'незаконопослушного',
        dative: 'незаконопослушному',
        accusative: 'незаконопослушное',
        instrumental: 'незаконопослушным',
        prepositional: 'незаконопослушном',
    },
  },
  {
    id: 'not_chaotic',
    oppositeId: 'not_lawful',
    name: {
        nominative: 'нехаотичное',
        genitive: 'нехаотичного',
        dative: 'нехаотичному',
        accusative: 'нехаотичное',
        instrumental: 'нехаотичным',
        prepositional: 'нехаотичном',
    },
  },
  {
    id: 'any_neutral',
    oppositeId: 'not_neutral',
    name: {
        nominative: 'любое нейтральное',
        genitive: 'любого нейтрального',
        dative: 'любому нейтральному',
        accusative: 'любое нейтральное',
        instrumental: 'любым нейтральным',
        prepositional: 'любом нейтральном',
    },
  },
  {
    id: 'lg',
    oppositeId: 'ce',
    name: {
        nominative: 'законопослушно-доброе',
        genitive: 'законопослушно-доброго',
        dative: 'законопослушно-доброму',
        accusative: 'законопослушно-доброе',
        instrumental: 'законопослушно-добрым',
        prepositional: 'законопослушно-добром',
    },
  },
  {
    id: 'ng',
    oppositeId: 'ne',
    name: {
        nominative: 'нейтрально-доброе',
        genitive: 'нейтрально-доброго',
        dative: 'нейтрально-доброму',
        accusative: 'нейтрально-доброе',
        instrumental: 'нейтрально-добрым',
        prepositional: 'нейтрально-добром',
    },
  },
  {
    id: 'cg',
    oppositeId: 'le',
    name: {
        nominative: 'хаотично-доброе',
        genitive: 'хаотично-доброго',
        dative: 'хаотично-доброму',
        accusative: 'хаотично-доброе',
        instrumental: 'хаотично-добрым',
        prepositional: 'хаотично-добром',
    },
  },
  {
    id: 'ln',
    oppositeId: 'cn',
    name: {
        nominative: 'законопослушно-нейтральное',
        genitive: 'законопослушно-нейтрального',
        dative: 'законопослушно-нейтральному',
        accusative: 'законопослушно-нейтральное',
        instrumental: 'законопослушно-нейтральным',
        prepositional: 'законопослушно-нейтральном',
    },
  },
  {
    id: 'n',
    oppositeId: null,
    name: {
        nominative: 'нейтральное',
        genitive: 'нейтрального',
        dative: 'нейтральному',
        accusative: 'нейтральное',
        instrumental: 'нейтральным',
        prepositional: 'нейтральном',
    },
  },
  {
    id: 'cn',
    oppositeId: 'ln',
    name: {
        nominative: 'хаотично-нейтральное',
        genitive: 'хаотично-нейтрального',
        dative: 'хаотично-нейтральному',
        accusative: 'хаотично-нейтральное',
        instrumental: 'хаотично-нейтральным',
        prepositional: 'хаотично-нейтральном',
    },
  },
  {
    id: 'le',
    oppositeId: 'cg',
    name: {
        nominative: 'законопослушно-злое',
        genitive: 'законопослушно-злого',
        dative: 'законопослушно-злому',
        accusative: 'законопослушно-злое',
        instrumental: 'законопослушно-злым',
        prepositional: 'законопослушно-злом',
    },
  },
  {
    id: 'ne',
    oppositeId: 'ng',
    name: {
        nominative: 'нейтрально-злое',
        genitive: 'нейтрально-злого',
        dative: 'нейтрально-злому',
        accusative: 'нейтрально-злое',
        instrumental: 'нейтрально-злым',
        prepositional: 'нейтрально-злом',
    },
  },
  {
    id: 'ce',
    oppositeId: 'lg',
    name: {
        nominative: 'хаотично-злое',
        genitive: 'хаотично-злого',
        dative: 'хаотично-злому',
        accusative: 'хаотично-злое',
        instrumental: 'хаотично-злым',
        prepositional: 'хаотично-злом',
    },
  },
]

export const dndAligmentCollection = listToCollectionById(dndAligmentList)
