import listToCollectionById from '@/utils/listToCollectionById'

const dndGodList = [
  {
    id: 'Azut',
    name: 'Азут, бог волшебников',
    aligmentId: 'ln',
    symbol: 'Очерченная огнём левая рука',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Amberli',
    name: 'Амберли, богиня морей',
    aligmentId: 'ce',
    symbol: 'Волны, расходящиеся влево и вправо',
    domainIdList: 'storm',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Baal',
    name: 'Баал, бог убийства',
    aligmentId: 'ne',
    symbol: 'Череп, окружённый кольцом капель крови',
    domainIdList: 'death',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Beshaba',
    name: 'Бешаба, богиня несчастья',
    aligmentId: 'ce',
    symbol: 'Чёрные оленьи рога',
    domainIdList: 'trick',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Bein',
    name: 'Бэйн, бог тирании',
    aligmentId: 'le',
    symbol: 'Чёрная кисть правой руки, собранная в кулак',
    domainIdList: 'war',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Vokin',
    name: 'Вокин, богиня торговли',
    aligmentId: 'n',
    symbol: 'Монета с изображением Вокин в профиль, смотрящей влево',
    domainIdList: ['trick', 'knowledge'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Gond',
    name: 'Гонд, бог ремёсел',
    aligmentId: 'n',
    symbol: 'Зубчатая шестерёнка с четырьмя спицами',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Deneir',
    name: 'Денеир, бог письменности',
    aligmentId: 'ng',
    symbol: 'Горящая свеча с открытым глазом',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Ilmater',
    name: 'Ильматер, бог стойкости',
    aligmentId: 'lg',
    symbol: 'Руки, на запястьях связанные красным шнуром',
    domainIdList: 'life',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Kelemvor',
    name: 'Келемвор, бог смерти',
    aligmentId: 'ln',
    symbol: 'Рука скелета, держащая уравновешенные весы',
    domainIdList: 'death',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Latander',
    name: 'Латандер, бог рождения и обновления',
    aligmentId: 'ng',
    symbol: 'Дорога, ведущая к восходу',
    domainIdList: ['life', 'light'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Leira',
    name: 'Лейра, богиня иллюзий',
    aligmentId: 'cn',
    symbol: 'Направленный вниз треугольник с вихрем тумана',
    domainIdList: 'trick',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Lliira',
    name: 'Ллиира, богиня веселья',
    aligmentId: 'cg',
    symbol: 'Треугольник из трёх шестиконечных звёзд',
    domainIdList: 'life',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Loviatar',
    name: 'Ловиатар, богиня боли',
    aligmentId: 'le',
    symbol: 'Девятихвостая плеть с шипами',
    domainIdList: 'death',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Mailikki',
    name: 'Майликки, богиня лесов',
    aligmentId: 'ng',
    symbol: 'Голова единорога',
    domainIdList: 'nature',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Malar',
    name: 'Малар, бог охоты',
    aligmentId: 'ce',
    symbol: 'Когтистая лапа',
    domainIdList: 'nature',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Mask',
    name: 'Маск, бог воров',
    aligmentId: 'cn',
    symbol: 'Чёрная маска',
    domainIdList: 'trick',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Milil',
    name: 'Милил, бог поэзии и песен',
    aligmentId: 'ng',
    symbol: 'Пятиструнная арфа из листьев',
    domainIdList: 'light',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Mirkul',
    name: 'Миркул, бог смерти',
    aligmentId: 'ne',
    symbol: 'Белый человеческий череп',
    domainIdList: 'death',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Mistra',
    name: 'Мистра, богиня магии',
    aligmentId: 'ng',
    symbol: 'Круг из семи звёзд или девять звёзд, окружающих текущий красный туман, или одна звезда',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Ogma',
    name: 'Огма, богиня знаний',
    aligmentId: 'n',
    symbol: 'Чистый свиток',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Oril',
    name: 'Ориль, богиня зимы',
    aligmentId: 'ne',
    symbol: 'Шестиконечная снежинка',
    domainIdList: ['storm', 'nature'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Savras',
    name: 'Саврас, бог предсказаний и судьбы',
    aligmentId: 'ln',
    symbol: 'Хрустальный шар с множеством глаз',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Selune',
    name: 'Селунэ, богиня луны',
    aligmentId: 'cg',
    symbol: 'Глаза, окружённые семью звёздами',
    domainIdList: ['life', 'knowledge'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Silvanus',
    name: 'Сильванус, бог дикой природы',
    aligmentId: 'n',
    symbol: 'Дубовый лист',
    domainIdList: 'nature',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'S`iuni',
    name: 'Сьюни, богиня любви и красоты',
    aligmentId: 'cg',
    symbol: 'Лицо прекрасной рыжеволосой женщины',
    domainIdList: ['life', 'light'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Talona',
    name: 'Талона, богиня болезней и ядов',
    aligmentId: 'ce',
    symbol: 'Три капли в треугольнике',
    domainIdList: 'death',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Talos',
    name: 'Талос, бог бурь',
    aligmentId: 'ce',
    symbol: 'Три молнии, бьющие из одной точки',
    domainIdList: 'storm',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Tempus',
    name: 'Темпус, бог войны',
    aligmentId: 'n',
    symbol: 'Вертикальный пламенеющий меч',
    domainIdList: 'war',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Torm',
    name: 'Торм, бог отваги и самопожертвования',
    aligmentId: 'lg',
    symbol: 'Правая латная рукавица белого цвета',
    domainIdList: 'war',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Timora',
    name: 'Тимора, богиня удачи',
    aligmentId: 'cg',
    symbol: 'Монета, решкой вверх',
    domainIdList: 'trick',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Tir',
    name: 'Тир, бог правосудия',
    aligmentId: 'lg',
    symbol: 'Сбалансированные весы на боевом молоте',
    domainIdList: 'war',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'KHelm',
    name: 'Хельм, бог защиты',
    aligmentId: 'ln',
    symbol: 'Глаз на левой латной рукавице',
    domainIdList: ['life', 'light'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Tcirik',
    name: 'Цирик, бог лжи',
    aligmentId: 'ce',
    symbol: 'Белый череп без нижней челюсти в ореоле чёрных или фиолетовых лучей',
    domainIdList: 'trick',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Chontia',
    name: 'Чонтиа, богиня земледелия',
    aligmentId: 'ng',
    symbol: 'Пучок колосьев или цветущая роза перед колосьями',
    domainIdList: 'life',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Shar',
    name: 'Шар, богиня тьмы и утрат',
    aligmentId: 'ne',
    symbol: 'Чёрный диск с фиолетовым контуром',
    domainIdList: ['trick', 'death'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Eldat',
    name: 'Эльдат, богиня мира',
    aligmentId: 'ng',
    symbol: 'Водопад, низвергающийся в спокойный пруд',
    domainIdList: ['life', 'nature'],
    panteonId: 'forgotten-realms',
  },
]

export const dndGodCollection = listToCollectionById(dndGodList)
