import listToCollectionById from '@/utils/listToCollectionById'

const dndGodList = [
  {
    id: 'Azut',
    name: {
      full: {
        nominative: 'Азут, бог волшебников',
        genitive: 'Азута, бога волшебников',
        dative: 'Азуту, богу волшебников',
        accusative: 'Азута, бога волшебников',
        instrumental: 'Азутом, богом волшебников',
        prepositional: 'Азуте, боге волшебников',
      },
      short: {
        nominative: 'Азут',
        genitive: 'Азута',
        dative: 'Азуту',
        accusative: 'Азута',
        instrumental: 'Азутом',
        prepositional: 'Азуте',
      },
    },
    aligmentId: 'ln',
    symbol: 'Очерченная огнём левая рука',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Amberli',
    name: {
      full: {
        nominative: 'Амберли, богиня морей',
        genitive: 'Амберли, богини морей',
        dative: 'Амберли, богине морей',
        accusative: 'Амберли, богиню морей',
        instrumental: 'Амберли, богиней морей',
        prepositional: 'Амберли, богине морей',
      },
      short: {
        nominative: 'Амберли',
        genitive: 'Амберли',
        dative: 'Амберли',
        accusative: 'Амберли',
        instrumental: 'Амберли',
        prepositional: 'Амберли',
      },
    },
    aligmentId: 'ce',
    symbol: 'Волны, расходящиеся влево и вправо',
    domainIdList: 'storm',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Baal',
    name: {
      full: {
        nominative: 'Баал, бог убийства',
        genitive: 'Баала, бога убийства',
        dative: 'Баалу, богу убийства',
        accusative: 'Баала, бога убийства',
        instrumental: 'Баалом, богом убийства',
        prepositional: 'Баале, боге убийства',
      },
      short: {
        nominative: 'Баал',
        genitive: 'Баала',
        dative: 'Баалу',
        accusative: 'Баала',
        instrumental: 'Баалом',
        prepositional: 'Баале',
      },
    },
    aligmentId: 'ne',
    symbol: 'Череп, окружённый кольцом капель крови',
    domainIdList: 'death',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Beshaba',
    name: {
      full: {
        nominative: 'Бешаба, богиня несчастья',
        genitive: 'Бешабы, богини несчастья',
        dative: 'Бешабе, богине несчастья',
        accusative: 'Бешабу, богиню несчастья',
        instrumental: 'Бешабой, богиней несчастья',
        prepositional: 'Бешабе, богине несчастья',
      },
      short: {
        nominative: 'Бешаба',
        genitive: 'Бешабы',
        dative: 'Бешабе',
        accusative: 'Бешабу',
        instrumental: 'Бешабой',
        prepositional: 'Бешабе',
      },
    },
    aligmentId: 'ce',
    symbol: 'Чёрные оленьи рога',
    domainIdList: 'trick',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Bein',
    name: {
      full: {
        nominative: 'Бэйн, бог тирании',
        genitive: 'Бэйна, бога тирании',
        dative: 'Бэйну, богу тирании',
        accusative: 'Бэйна, бога тирании',
        instrumental: 'Бэйном, богом тирании',
        prepositional: 'Бэйне, боге тирании',
      },
      short: {
        nominative: 'Бэйн',
        genitive: 'Бэйна',
        dative: 'Бэйну',
        accusative: 'Бэйна',
        instrumental: 'Бэйном',
        prepositional: 'Бэйне',
      },
    },
    aligmentId: 'le',
    symbol: 'Чёрная кисть правой руки, собранная в кулак',
    domainIdList: 'war',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Vokin',
    name: {
      full: {
        nominative: 'Вокин, богиня торговли',
        genitive: 'Вокин, богини торговли',
        dative: 'Вокин, богине торговли',
        accusative: 'Вокин, богиню торговли',
        instrumental: 'Вокин, богиней торговли',
        prepositional: 'Вокин, богине торговли',
      },
      short: {
        nominative: 'Вокин',
        genitive: 'Вокин',
        dative: 'Вокин',
        accusative: 'Вокин',
        instrumental: 'Вокин',
        prepositional: 'Вокин',
      },
    },
    aligmentId: 'n',
    symbol: 'Монета с изображением Вокин в профиль, смотрящей влево',
    domainIdList: ['trick', 'knowledge'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Gond',
    name: {
      full: {
        nominative: 'Гонд, бог ремёсел',
        genitive: 'Гонда, бога ремёсел',
        dative: 'Гонду, богу ремёсел',
        accusative: 'Гонда, бога ремёсел',
        instrumental: 'Гондом, богом ремёсел',
        prepositional: 'Гонде, боге ремёсел',
      },
      short: {
        nominative: 'Гонд',
        genitive: 'Гонда',
        dative: 'Гонду',
        accusative: 'Гонда',
        instrumental: 'Гондом',
        prepositional: 'Гонде',
      },
    },
    aligmentId: 'n',
    symbol: 'Зубчатая шестерёнка с четырьмя спицами',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Deneir',
    name: {
      full: {
        nominative: 'Денеир, бог письменности',
        genitive: 'Денеира, бога письменности',
        dative: 'Денеиру, богу письменности',
        accusative: 'Денеира, бога письменности',
        instrumental: 'Денеиром, богом письменности',
        prepositional: 'Денеире, боге письменности',
      },
      short: {
        nominative: 'Денеир',
        genitive: 'Денеира',
        dative: 'Денеиру',
        accusative: 'Денеира',
        instrumental: 'Денеиром',
        prepositional: 'Денеире',
      },
    },
    aligmentId: 'ng',
    symbol: 'Горящая свеча с открытым глазом',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Ilmater',
    name: {
      full: {
        nominative: 'Ильматер, бог стойкости',
        genitive: 'Ильматера, бога стойкости',
        dative: 'Ильматеру, богу стойкости',
        accusative: 'Ильматера, бога стойкости',
        instrumental: 'Ильматером, богом стойкости',
        prepositional: 'Ильматере, боге стойкости',
      },
      short: {
        nominative: 'Ильматер',
        genitive: 'Ильматера',
        dative: 'Ильматеру',
        accusative: 'Ильматера',
        instrumental: 'Ильматером',
        prepositional: 'Ильматере',
      },
    },
    aligmentId: 'lg',
    symbol: 'Руки, на запястьях связанные красным шнуром',
    domainIdList: 'life',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Kelemvor',
    name: {
      full: {
        nominative: 'Келемвор, бог смерти',
        genitive: 'Келемвора, бога смерти',
        dative: 'Келемвору, богу смерти',
        accusative: 'Келемвора, бога смерти',
        instrumental: 'Келемвором, богом смерти',
        prepositional: 'Келемворе, боге смерти',
      },
      short: {
        nominative: 'Келемвор',
        genitive: 'Келемвора',
        dative: 'Келемвору',
        accusative: 'Келемвора',
        instrumental: 'Келемвором',
        prepositional: 'Келемворе',
      },
    },
    aligmentId: 'ln',
    symbol: 'Рука скелета, держащая уравновешенные весы',
    domainIdList: 'death',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Latander',
    name: {
      full: {
        nominative: 'Латандер, бог рождения и обновления',
        genitive: 'Латандера, бога рождения и обновления',
        dative: 'Латандеру, богу рождения и обновления',
        accusative: 'Латандера, бога рождения и обновления',
        instrumental: 'Латандером, богом рождения и обновления',
        prepositional: 'Латандере, боге рождения и обновления',
      },
      short: {
        nominative: 'Латандер',
        genitive: 'Латандера',
        dative: 'Латандеру',
        accusative: 'Латандера',
        instrumental: 'Латандером',
        prepositional: 'Латандере',
      },
    },
    aligmentId: 'ng',
    symbol: 'Дорога, ведущая к восходу',
    domainIdList: ['life', 'light'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Leira',
    name: {
      full: {
        nominative: 'Лейра, богиня иллюзий',
        genitive: 'Лейры, богини иллюзий',
        dative: 'Лейре, богине иллюзий',
        accusative: 'Лейру, богиню иллюзий',
        instrumental: 'Лейрой, богиней иллюзий',
        prepositional: 'Лейре, богине иллюзий',
      },
      short: {
        nominative: 'Лейра',
        genitive: 'Лейры',
        dative: 'Лейре',
        accusative: 'Лейру',
        instrumental: 'Лейрой',
        prepositional: 'Лейре',
      },
    },
    aligmentId: 'cn',
    symbol: 'Направленный вниз треугольник с вихрем тумана',
    domainIdList: 'trick',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Lliira',
    name: {
      full: {
        nominative: 'Ллиира, богиня веселья',
        genitive: 'Ллииры, богини веселья',
        dative: 'Ллиире, богине веселья',
        accusative: 'Ллииру, богиню веселья',
        instrumental: 'Ллиирой, богиней веселья',
        prepositional: 'Ллиире, богине веселья',
      },
      short: {
        nominative: 'Ллиира',
        genitive: 'Ллииры',
        dative: 'Ллиире',
        accusative: 'Ллииру',
        instrumental: 'Ллиирой',
        prepositional: 'Ллиире',
      },
    },
    aligmentId: 'cg',
    symbol: 'Треугольник из трёх шестиконечных звёзд',
    domainIdList: 'life',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Loviatar',
    name: {
      full: {
        nominative: 'Ловиатар, богиня боли',
        genitive: 'Ловиатар, богини боли',
        dative: 'Ловиатар, богине боли',
        accusative: 'Ловиатар, богиню боли',
        instrumental: 'Ловиатар, богиней боли',
        prepositional: 'Ловиатар, богине боли',
      },
      short: {
        nominative: 'Ловиатар',
        genitive: 'Ловиатар',
        dative: 'Ловиатар',
        accusative: 'Ловиатар',
        instrumental: 'Ловиатар',
        prepositional: 'Ловиатар',
      },
    },
    aligmentId: 'le',
    symbol: 'Девятихвостая плеть с шипами',
    domainIdList: 'death',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Mailikki',
    name: {
      full: {
        nominative: 'Майликки, богиня лесов',
        genitive: 'Майликки, богини лесов',
        dative: 'Майликки, богине лесов',
        accusative: 'Майликки, богиню лесов',
        instrumental: 'Майликки, богиней лесов',
        prepositional: 'Майликки, богине лесов',
      },
      short: {
        nominative: 'Майликки',
        genitive: 'Майликки',
        dative: 'Майликки',
        accusative: 'Майликки',
        instrumental: 'Майликки',
        prepositional: 'Майликки',
      },
    },
    aligmentId: 'ng',
    symbol: 'Голова единорога',
    domainIdList: 'nature',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Malar',
    name: {
      full: {
        nominative: 'Малар, бог охоты',
        genitive: 'Малара, бога охоты',
        dative: 'Малару, богу охоты',
        accusative: 'Малара, бога охоты',
        instrumental: 'Маларом, богом охоты',
        prepositional: 'Маларе, боге охоты',
      },
      short: {
        nominative: 'Малар',
        genitive: 'Малара',
        dative: 'Малару',
        accusative: 'Малара',
        instrumental: 'Маларом',
        prepositional: 'Маларе',
      },
    },
    aligmentId: 'ce',
    symbol: 'Когтистая лапа',
    domainIdList: 'nature',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Mask',
    name: {
      full: {
        nominative: 'Маск, бог воров',
        genitive: 'Маска, бога воров',
        dative: 'Маску, богу воров',
        accusative: 'Маска, бога воров',
        instrumental: 'Маском, богом воров',
        prepositional: 'Маске, боге воров',
      },
      short: {
        nominative: 'Маск',
        genitive: 'Маска',
        dative: 'Маску',
        accusative: 'Маска',
        instrumental: 'Маском',
        prepositional: 'Маске',
      },
    },
    aligmentId: 'cn',
    symbol: 'Чёрная маска',
    domainIdList: 'trick',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Milil',
    name: {
      full: {
        nominative: 'Милил, бог поэзии и песен',
        genitive: 'Милила, бога поэзии и песен',
        dative: 'Милилу, богу поэзии и песен',
        accusative: 'Милила, бога поэзии и песен',
        instrumental: 'Милилом, богом поэзии и песен',
        prepositional: 'Милиле, боге поэзии и песен',
      },
      short: {
        nominative: 'Милил',
        genitive: 'Милила',
        dative: 'Милилу',
        accusative: 'Милила',
        instrumental: 'Милилом',
        prepositional: 'Милиле',
      },
    },
    aligmentId: 'ng',
    symbol: 'Пятиструнная арфа из листьев',
    domainIdList: 'light',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Mirkul',
    name: {
      full: {
        nominative: 'Миркул, бог смерти',
        genitive: 'Миркула, бога смерти',
        dative: 'Миркулу, богу смерти',
        accusative: 'Миркула, бога смерти',
        instrumental: 'Миркулом, богом смерти',
        prepositional: 'Миркуле, боге смерти',
      },
      short: {
        nominative: 'Миркул',
        genitive: 'Миркула',
        dative: 'Миркулу',
        accusative: 'Миркула',
        instrumental: 'Миркулом',
        prepositional: 'Миркуле',
      },
    },
    aligmentId: 'ne',
    symbol: 'Белый человеческий череп',
    domainIdList: 'death',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Mistra',
    name: {
      full: {
        nominative: 'Мистра, богиня магии',
        genitive: 'Мистры, богини магии',
        dative: 'Мистре, богине магии',
        accusative: 'Мистру, богиню магии',
        instrumental: 'Мистрой, богиней магии',
        prepositional: 'Мистре, богине магии',
      },
      short: {
        nominative: 'Мистра',
        genitive: 'Мистры',
        dative: 'Мистре',
        accusative: 'Мистру',
        instrumental: 'Мистрой',
        prepositional: 'Мистре',
      },
    },
    aligmentId: 'ng',
    symbol: 'Круг из семи звёзд или девять звёзд, окружающих текущий красный туман, или одна звезда',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Ogma',
    name: {
      full: {
        nominative: 'Огма, богиня знаний',
        genitive: 'Огмы, богини знаний',
        dative: 'Огме, богине знаний',
        accusative: 'Огму, богиню знаний',
        instrumental: 'Огмой, богиней знаний',
        prepositional: 'Огме, богине знаний',
      },
      short: {
        nominative: 'Огма',
        genitive: 'Огмы',
        dative: 'Огме',
        accusative: 'Огму',
        instrumental: 'Огмой',
        prepositional: 'Огме',
      },
    },
    aligmentId: 'n',
    symbol: 'Чистый свиток',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Oril',
    name: {
      full: {
        nominative: 'Ориль, богиня зимы',
        genitive: 'Ориль, богини зимы',
        dative: 'Ориль, богине зимы',
        accusative: 'Ориль, богиню зимы',
        instrumental: 'Ориль, богиней зимы',
        prepositional: 'Ориль, богине зимы',
      },
      short: {
        nominative: 'Ориль',
        genitive: 'Ориль',
        dative: 'Ориль',
        accusative: 'Ориль',
        instrumental: 'Ориль',
        prepositional: 'Ориль',
      },
    },
    aligmentId: 'ne',
    symbol: 'Шестиконечная снежинка',
    domainIdList: ['storm', 'nature'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Savras',
    name: {
      full: {
        nominative: 'Саврас, бог предсказаний и судьбы',
        genitive: 'Савраса, бога предсказаний и судьбы',
        dative: 'Саврасу, богу предсказаний и судьбы',
        accusative: 'Савраса, бога предсказаний и судьбы',
        instrumental: 'Саврасом, богом предсказаний и судьбы',
        prepositional: 'Саврасе, боге предсказаний и судьбы',
      },
      short: {
        nominative: 'Саврас',
        genitive: 'Савраса',
        dative: 'Саврасу',
        accusative: 'Савраса',
        instrumental: 'Саврасом',
        prepositional: 'Саврасе',
      },
    },
    aligmentId: 'ln',
    symbol: 'Хрустальный шар с множеством глаз',
    domainIdList: 'knowledge',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Selune',
    name: {
      full: {
        nominative: 'Селунэ, богиня луны',
        genitive: 'Селунэ, богини луны',
        dative: 'Селунэ, богине луны',
        accusative: 'Селунэ, богиню луны',
        instrumental: 'Селунэ, богиней луны',
        prepositional: 'Селунэ, богине луны',
      },
      short: {
        nominative: 'Селунэ',
        genitive: 'Селунэ',
        dative: 'Селунэ',
        accusative: 'Селунэ',
        instrumental: 'Селунэ',
        prepositional: 'Селунэ',
      },
    },
    aligmentId: 'cg',
    symbol: 'Глаза, окружённые семью звёздами',
    domainIdList: ['life', 'knowledge'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Silvanus',
    name: {
      full: {
        nominative: 'Сильванус, бог дикой природы',
        genitive: 'Сильвануса, бога дикой природы',
        dative: 'Сильванусу, богу дикой природы',
        accusative: 'Сильвануса, бога дикой природы',
        instrumental: 'Сильванусом, богом дикой природы',
        prepositional: 'Сильванусе, боге дикой природы',
      },
      short: {
        nominative: 'Сильванус',
        genitive: 'Сильвануса',
        dative: 'Сильванусу',
        accusative: 'Сильвануса',
        instrumental: 'Сильванусом',
        prepositional: 'Сильванусе',
      },
    },
    aligmentId: 'n',
    symbol: 'Дубовый лист',
    domainIdList: 'nature',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'S`iuni',
    name: {
      full: {
        nominative: 'Сьюни, богиня любви и красоты',
        genitive: 'Сьюни, богини любви и красоты',
        dative: 'Сьюни, богине любви и красоты',
        accusative: 'Сьюни, богиню любви и красоты',
        instrumental: 'Сьюни, богиней любви и красоты',
        prepositional: 'Сьюни, богине любви и красоты',
      },
      short: {
        nominative: 'Сьюни',
        genitive: 'Сьюни',
        dative: 'Сьюни',
        accusative: 'Сьюни',
        instrumental: 'Сьюни',
        prepositional: 'Сьюни',
      },
    },
    aligmentId: 'cg',
    symbol: 'Лицо прекрасной рыжеволосой женщины',
    domainIdList: ['life', 'light'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Talona',
    name: {
      full: {
        nominative: 'Талона, богиня болезней и ядов',
        genitive: 'Талоны, богини болезней и ядов',
        dative: 'Талоне, богине болезней и ядов',
        accusative: 'Талону, богиню болезней и ядов',
        instrumental: 'Талоной, богиней болезней и ядов',
        prepositional: 'Талоне, богине болезней и ядов',
      },
      short: {
        nominative: 'Талона',
        genitive: 'Талоны',
        dative: 'Талоне',
        accusative: 'Талону',
        instrumental: 'Талоной',
        prepositional: 'Талоне',
      },
    },
    aligmentId: 'ce',
    symbol: 'Три капли в треугольнике',
    domainIdList: 'death',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Talos',
    name: {
      full: {
        nominative: 'Талос, бог бурь',
        genitive: 'Талоса, бога бурь',
        dative: 'Талосу, богу бурь',
        accusative: 'Талоса, бога бурь',
        instrumental: 'Талосом, богом бурь',
        prepositional: 'Талосе, боге бурь',
      },
      short: {
        nominative: 'Талос',
        genitive: 'Талоса',
        dative: 'Талосу',
        accusative: 'Талоса',
        instrumental: 'Талосом',
        prepositional: 'Талосе',
      },
    },
    aligmentId: 'ce',
    symbol: 'Три молнии, бьющие из одной точки',
    domainIdList: 'storm',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Tempus',
    name: {
      full: {
        nominative: 'Темпус, бог войны',
        genitive: 'Темпуса, бога войны',
        dative: 'Темпусу, богу войны',
        accusative: 'Темпуса, бога войны',
        instrumental: 'Темпусом, богом войны',
        prepositional: 'Темпусе, боге войны',
      },
      short: {
        nominative: 'Темпус',
        genitive: 'Темпуса',
        dative: 'Темпусу',
        accusative: 'Темпуса',
        instrumental: 'Темпусом',
        prepositional: 'Темпусе',
      },
    },
    aligmentId: 'n',
    symbol: 'Вертикальный пламенеющий меч',
    domainIdList: 'war',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Torm',
    name: {
      full: {
        nominative: 'Торм, бог отваги и самопожертвования',
        genitive: 'Торма, бога отваги и самопожертвования',
        dative: 'Торму, богу отваги и самопожертвования',
        accusative: 'Торма, бога отваги и самопожертвования',
        instrumental: 'Тормом, богом отваги и самопожертвования',
        prepositional: 'Торме, боге отваги и самопожертвования',
      },
      short: {
        nominative: 'Торм',
        genitive: 'Торма',
        dative: 'Торму',
        accusative: 'Торма',
        instrumental: 'Тормом',
        prepositional: 'Торме',
      },
    },
    aligmentId: 'lg',
    symbol: 'Правая латная рукавица белого цвета',
    domainIdList: 'war',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Timora',
    name: {
      full: {
        nominative: 'Тимора, богиня удачи',
        genitive: 'Тиморы, богини удачи',
        dative: 'Тиморе, богине удачи',
        accusative: 'Тимору, богиню удачи',
        instrumental: 'Тиморой, богиней удачи',
        prepositional: 'Тиморе, богине удачи',
      },
      short: {
        nominative: 'Тимора',
        genitive: 'Тиморы',
        dative: 'Тиморе',
        accusative: 'Тимору',
        instrumental: 'Тиморой',
        prepositional: 'Тиморе',
      },
    },
    aligmentId: 'cg',
    symbol: 'Монета, решкой вверх',
    domainIdList: 'trick',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Tir',
    name: {
      full: {
        nominative: 'Тир, бог правосудия',
        genitive: 'Тира, бога правосудия',
        dative: 'Тиру, богу правосудия',
        accusative: 'Тира, бога правосудия',
        instrumental: 'Тиром, богом правосудия',
        prepositional: 'Тире, боге правосудия',
      },
      short: {
        nominative: 'Тир',
        genitive: 'Тира',
        dative: 'Тиру',
        accusative: 'Тира',
        instrumental: 'Тиром',
        prepositional: 'Тире',
      },
    },
    aligmentId: 'lg',
    symbol: 'Сбалансированные весы на боевом молоте',
    domainIdList: 'war',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'KHelm',
    name: {
      full: {
        nominative: 'Хельм, бог защиты',
        genitive: 'Хельма, бога защиты',
        dative: 'Хельму, богу защиты',
        accusative: 'Хельма, бога защиты',
        instrumental: 'Хельмом, богом защиты',
        prepositional: 'Хельме, боге защиты',
      },
      short: {
        nominative: 'Хельм',
        genitive: 'Хельма',
        dative: 'Хельму',
        accusative: 'Хельма',
        instrumental: 'Хельмом',
        prepositional: 'Хельме',
      },
    },
    aligmentId: 'ln',
    symbol: 'Глаз на левой латной рукавице',
    domainIdList: ['life', 'light'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Tcirik',
    name: {
      full: {
        nominative: 'Цирик, бог лжи',
        genitive: 'Цирика, бога лжи',
        dative: 'Цирику, богу лжи',
        accusative: 'Цирика, бога лжи',
        instrumental: 'Цириком, богом лжи',
        prepositional: 'Цирике, боге лжи',
      },
      short: {
        nominative: 'Цирик',
        genitive: 'Цирика',
        dative: 'Цирику',
        accusative: 'Цирика',
        instrumental: 'Цириком',
        prepositional: 'Цирике',
      },
    },
    aligmentId: 'ce',
    symbol: 'Белый череп без нижней челюсти в ореоле чёрных или фиолетовых лучей',
    domainIdList: 'trick',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Chontia',
    name: {
      full: {
        nominative: 'Чонтиа, богиня земледелия',
        genitive: 'Чонтиы, богини земледелия',
        dative: 'Чонтие, богине земледелия',
        accusative: 'Чонтиу, богиню земледелия',
        instrumental: 'Чонтиой, богиней земледелия',
        prepositional: 'Чонтие, богине земледелия',
      },
      short: {
        nominative: 'Чонтиа',
        genitive: 'Чонтиы',
        dative: 'Чонтие',
        accusative: 'Чонтиу',
        instrumental: 'Чонтиой',
        prepositional: 'Чонтие',
      },
    },
    aligmentId: 'ng',
    symbol: 'Пучок колосьев или цветущая роза перед колосьями',
    domainIdList: 'life',
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Shar',
    name: {
      full: {
        nominative: 'Шар, богиня тьмы и утрат',
        genitive: 'Шар, богини тьмы и утрат',
        dative: 'Шар, богине тьмы и утрат',
        accusative: 'Шар, богиню тьмы и утрат',
        instrumental: 'Шар, богиней тьмы и утрат',
        prepositional: 'Шар, богине тьмы и утрат',
      },
      short: {
        nominative: 'Шар',
        genitive: 'Шар',
        dative: 'Шар',
        accusative: 'Шар',
        instrumental: 'Шар',
        prepositional: 'Шар',
      },
    },
    aligmentId: 'ne',
    symbol: 'Чёрный диск с фиолетовым контуром',
    domainIdList: ['trick', 'death'],
    panteonId: 'forgotten-realms',
  },
  {
    id: 'Eldat',
    name: {
      full: {
        nominative: 'Эльдат, богиня мира',
        genitive: 'Эльдат, богини мира',
        dative: 'Эльдат, богине мира',
        accusative: 'Эльдат, богиню мира',
        instrumental: 'Эльдат, богиней мира',
        prepositional: 'Эльдат, богине мира',
      },
      short: {
        nominative: 'Эльдат',
        genitive: 'Эльдат',
        dative: 'Эльдат',
        accusative: 'Эльдат',
        instrumental: 'Эльдат',
        prepositional: 'Эльдат',
      },
    },
    aligmentId: 'ng',
    symbol: 'Водопад, низвергающийся в спокойный пруд',
    domainIdList: ['life', 'nature'],
    panteonId: 'forgotten-realms',
  },
]

export const dndGodCollection = listToCollectionById(dndGodList)
