import _ from 'lodash'

import SEARCH_PROP_NAME from '@/constants/SEARCH_PROP_NAME'

import listToCollectionById from '@/utils/listToCollectionById'

const dndItemList = [
  {
    id: 'styoganny`i` dospekh',
    name: 'Стёганный доспех',
    nameEn: '',
    description: 'Стёганый доспех состоит из прошитых слоёв ткани и ватина.',
    cost: 500,
    weight: 8,
    blockHiding: true,
    acChangeTo: 11,
    acUseDexMod: true,
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Лёгкие доспехи',
  },
  {
    id: 'kozhany`i` dospekh',
    name: 'Кожаный доспех',
    nameEn: '',
    description: 'Нагрудник и плечи этого доспеха изготовлены из кожи, вываренной в масле. Остальные части доспеха сделаны из более мягких и гибких материалов.',
    cost: 1000,
    weight: 10,
    acChangeTo: 11,
    acUseDexMod: true,
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Лёгкие доспехи',
  },
  {
    id: 'dospekh iz proclyopannoi` kozhi',
    name: 'Доспех из проклёпанной кожи',
    nameEn: '',
    description: 'Изготовленный из крепкой, но гибкой кожи проклёпанный доспех усилен тесно расположенными шипами или заклёпками.',
    cost: 4500,
    weight: 13,
    acChangeTo: 12,
    acUseDexMod: true,
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Лёгкие доспехи',
  },
  {
    id: 'shkurny`i` dospekh',
    name: 'Шкурный доспех',
    nameEn: '',
    description: 'Этот грубый доспех состоит из толстых мехов и шкур. Обычно их носят племена варваров, злые гуманоиды и прочие народы, у которых нет инструментов и материалов для создания более качественных доспехов.',
    cost: 1000,
    weight: 12,
    acChangeTo: 12,
    acUseDexMod: true,
    acDexModMax: 2,
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Средние доспехи',
  },
  {
    id: 'kol`chuzhnaia rubaha',
    name: 'Кольчужная рубаха',
    nameEn: '',
    description: 'Сделанная из переплетённых металлических колец кольчужная рубаха носится между слоями одежды или кожи. Этот доспех предоставляет умеренную защиту торса и заглушает звон колец внешним покрытием.',
    cost: 5000,
    weight: 20,
    acChangeTo: 13,
    acUseDexMod: true,
    acDexModMax: 2,
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Средние доспехи',
  },
  {
    id: 'cheshui`chaty`i` dospekh',
    name: 'Чешуйчатый доспех',
    nameEn: '',
    description: 'Этот доспех состоит из кожаных куртки и поножей (а также, возможно, отдельной юбки), покрытых перекрывающимися кусочками металла, похожими на рыбную чешую. В комплект входят рукавицы.',
    cost: 5000,
    weight: 45,
    blockHiding: true,
    acChangeTo: 14,
    acUseDexMod: true,
    acDexModMax: 2,
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Средние доспехи',
  },
  {
    id: 'kirasa',
    name: 'Кираса',
    nameEn: '',
    description: 'Этот доспех состоит из подогнанного металлического панциря, носимого с подкладкой из кожи. Несмотря на то, что руки и ноги остаются практически без защиты, этот доспех хорошо защищает жизненно важные органы, оставляя владельцу относительную подвижность.',
    cost: 40000,
    weight: 20,
    acChangeTo: 14,
    acUseDexMod: true,
    acDexModMax: 2,
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Средние доспехи',
  },
  {
    id: 'polulaty',
    name: 'Полулаты',
    nameEn: '',
    description: 'Полулаты состоят из сформированных металлических пластин, покрывающих большую часть тела владельца. В них не входит защита для ног кроме простых поножей, закреплённых кожаными ремнями.',
    cost: 75000,
    weight: 40,
    blockHiding: true,
    acChangeTo: 15,
    acUseDexMod: true,
    acDexModMax: 2,
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Средние доспехи',
  },
  {
    id: 'kolechny`i` dospekh',
    name: 'Колечный доспех',
    nameEn: '',
    description: 'Это кожаный доспех с нашитыми на него толстыми кольцами. Эти кольца усиливают доспех от ударов мечей и топоров. Колечный доспех хуже кольчуги, и обычно его носят только те, кто не могут позволить себе доспех получше.',
    cost: 3000,
    weight: 40,
    blockHiding: true,
    acChangeTo: 14,
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Тяжёлые доспехи',
  },
  {
    id: 'kol`chuga',
    name: 'Кольчуга',
    nameEn: 'Chain mail',
    description: 'Изготовленная из переплетающихся металлических колец кольчуга включает также слой стёганой ткани, надеваемой под низ, дабы предотвратить натирание и смягчать удары. В комплект входят рукавицы.',
    cost: 7500,
    weight: 55,
    blockHiding: true,
    acChangeTo: 16,
    requirementList: [
      {
        type: 'param',
        paramType: 'str',
        min: 13,
      },
    ],
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Тяжёлые доспехи',
  },
  {
    id: 'naborny`i` dospekh',
    name: 'Наборный доспех',
    nameEn: '',
    description: 'Этот доспех состоит из узких вертикальных металлических пластин, приклёпанных к кожаной подложке, носимой поверх слоя ватина. Соединения защищаются кольчужным полотном.',
    cost: 20000,
    weight: 60,
    blockHiding: true,
    acChangeTo: 17,
    requirementList: [
      {
        type: 'param',
        paramType: 'str',
        min: 15,
      },
    ],
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Тяжёлые доспехи',
  },
  {
    id: 'laty',
    name: 'Латы',
    nameEn: '',
    description: 'Латы состоят из сформированных металлических пластин, покрывающих всё тело. В комплект лат входят рукавицы, тяжёлые кожаные сапоги, шлем с забралом, и толстый слой ватина. Ремешки и пряжки распределяют вес по всему телу.',
    cost: 150000,
    weight: 65,
    blockHiding: true,
    acChangeTo: 18,
    requirementList: [
      {
        type: 'param',
        paramType: 'str',
        min: 15,
      },
    ],
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Тяжёлые доспехи',
  },
  {
    id: 'shchit',
    name: 'Щит',
    nameEn: '',
    description: '',
    cost: 1000,
    weight: 6,
    acBonus: 2,
    source: 'PHB:145',
    category: 'Доспехи',
    subcategory: 'Щиты',
  },
  {
    id: 'boevoi` posokh',
    name: 'Боевой посох',
    nameEn: '',
    description: 'Урон 1к6 дробящий. Универсальное (1к8)',
    damage: {
      cubeType: 6,
      cubeCount: 1,
    },
    cost: 20,
    damageType: 'bludgeoning',
    weight: 4,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое рукопашное оружие',
  },
  {
    id: 'bulava',
    name: 'Булава',
    nameEn: '',
    description: 'Урон 1к6 дробящий',
    damage: {
      cubeType: 6,
      cubeCount: 1,
    },
    cost: 500,
    damageType: 'bludgeoning',
    weight: 4,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое рукопашное оружие',
  },
  {
    id: 'dubinka',
    name: 'Дубинка',
    nameEn: '',
    damage: {
      cubeType: 4,
      cubeCount: 1,
    },
    description: 'Урон 1к4 дробящий. Лёгкое',
    cost: 10,
    damageType: 'bludgeoning',
    weight: 2,
    isLight: true,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое рукопашное оружие',
  },
  {
    id: 'kinzhal',
    name: 'Кинжал',
    nameEn: '',
    description: 'Урон 1к4 колющий. Лёгкое, метательное (дис. 20/60), фехтовальное',
    damage: {
      cubeType: 4,
      cubeCount: 1,
    },
    range: {
      normal: 20,
      max: 60,
    },
    isLight: true,
    isThrown: true,
    isFinesse: true,
    cost: 200,
    damageType: 'piercing',
    weight: 1,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое рукопашное оружие',
  },
  {
    id: 'kop`yo',
    name: 'Копьё',
    nameEn: '',
    description: 'Урон 1к6 колющий. Метательное (дис. 20/60), универсальное (1к8)',
    damage: {
      cubeType: 6,
      cubeCount: 1,
    },
    range: {
      normal: 20,
      max: 60,
    },
    isThrown: true,
    cost: 100,
    damageType: 'piercing',
    weight: 3,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое рукопашное оружие',
  },
  {
    id: 'lyogkii` molot',
    name: 'Лёгкий молот',
    nameEn: '',
    description: 'Урон 1к4 дробящий. Лёгкое, метательное (дис. 20/60)',
    damage: {
      cubeType: 4,
      cubeCount: 1,
    },
    range: {
      normal: 20,
      max: 60,
    },
    isLight: true,
    isThrown: true,
    cost: 200,
    damageType: 'bludgeoning',
    weight: 2,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое рукопашное оружие',
  },
  {
    id: 'metatel`noe kop`yo',
    name: 'Метательное копьё',
    nameEn: '',
    description: 'Урон 1к6 колющий. Метательное (дис. 30/120)',
    damage: {
      cubeType: 6,
      cubeCount: 1,
    },
    range: {
      normal: 30,
      max: 120,
    },
    isThrown: true,
    cost: 50,
    damageType: 'piercing',
    weight: 2,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое рукопашное оружие',
  },
  {
    id: 'palitca',
    name: 'Палица',
    nameEn: '',
    description: 'Урон 1к8 колющий. Двуручное',
    damage: {
      cubeType: 8,
      cubeCount: 1,
    },
    isTwoHanded: true,
    cost: 20,
    damageType: 'piercing',
    weight: 10,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое рукопашное оружие',
  },
  {
    id: 'ruchnoi` topor',
    name: 'Ручной топор',
    nameEn: '',
    description: 'Урон 1к6 рубящий. Лёгкое, метательное (дис. 20/60)',
    damage: {
      cubeType: 6,
      cubeCount: 1,
    },
    range: {
      normal: 20,
      max: 60,
    },
    isLight: true,
    isThrown: true,
    cost: 500,
    damageType: 'slashing',
    weight: 10,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое рукопашное оружие',
  },
  {
    id: 'serp',
    name: 'Серп',
    nameEn: '',
    description: 'Урон 1к4 рубящий. Лёгкое',
    damage: {
      cubeType: 4,
      cubeCount: 1,
    },
    isLight: true,
    damageType: 'slashing',
    cost: 100,
    weight: 2,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое рукопашное оружие',
  },
  {
    id: 'ilkva',
    name: 'Илква',
    nameEn: 'Yklwa',
    description: 'Урон 1к8 колющий; Метательное (дис. 10/30). Иклва — это традиционное оружие ближнего боя чультских воинов. Иклва состоит из 3-футой деревянной рукояти со стальным или каменным лезвием длиной до 18 дюймов.',
    damage: {
      cubeType: 8,
      cubeCount: 1,
    },
    range: {
      normal: 10,
      max: 30,
    },
    isThrown: true,
    cost: 100,
    damageType: 'piercing',
    source: 'ToA:32',
    category: 'Оружие',
    subcategory: 'Простое рукопашное оружие',
  },
  {
    id: 'arbalet, lyogkii',
    name: 'Арбалет, лёгкий',
    nameEn: '',
    description: 'Урон 1к8 колющий. Боеприпас (дис. 80/320), двуручное, перезарядка',
    damage: {
      cubeType: 8,
      cubeCount: 1,
    },
    range: {
      normal: 80,
      max: 320,
    },
    isTwoHanded: true,
    isReloading: true,
    needAmmo: true,
    cost: 2500,
    damageType: 'piercing',
    weight: 5,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое дальнобойное оружие',
  },
  {
    id: 'drotik',
    name: 'Дротик',
    nameEn: '',
    description: 'Урон 1к4 колющий. Метательное (дис. 20/60), фехтовальное',
    damage: {
      cubeType: 4,
      cubeCount: 1,
    },
    range: {
      normal: 20,
      max: 60,
    },
    isThrown: true,
    isFinesse: true,
    cost: 5,
    damageType: 'piercing',
    weight: '0.25',
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое дальнобойное оружие',
  },
  {
    id: 'korotkii` luk',
    name: 'Короткий лук',
    nameEn: 'Shortbow',
    description: 'Урон 1к6 колющий. Боеприпас (дис. 80/320), двуручное',
    damage: {
      cubeType: 6,
      cubeCount: 1,
    },
    range: {
      normal: 80,
      max: 320,
    },
    isTwoHanded: true,
    needAmmo: true,
    cost: 2500,
    damageType: 'piercing',
    weight: 2,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое дальнобойное оружие',
  },
  {
    id: 'prashcha',
    name: 'Праща',
    nameEn: '',
    description: 'Урон 1к4 дробящий. Боеприпас (дис. 30/120)',
    damage: {
      cubeType: 4,
      cubeCount: 1,
    },
    range: {
      normal: 30,
      max: 120,
    },
    needAmmo: true,
    cost: 10,
    damageType: 'bludgeoning',
    weight: 0,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Простое дальнобойное оружие',
  },
  {
    id: 'alebarda',
    name: 'Алебарда',
    nameEn: '',
    description: 'Урон 1к10 рубящий. Двуручное, досягаемость, тяжёлое',
    damage: {
      cubeType: 10,
      cubeCount: 1,
    },
    isTwoHanded: true,
    isReach: true,
    isHeavy: true,
    cost: 2000,
    damageType: 'slashing',
    weight: 6,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'boevaia kirka',
    name: 'Боевая кирка',
    nameEn: '',
    description: 'Урон 1к8 колющий',
    damage: {
      cubeType: 8,
      cubeCount: 1,
    },
    cost: 500,
    damageType: 'piercing',
    weight: 2,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'boevoi` molot',
    name: 'Боевой молот',
    nameEn: '',
    description: 'Урон 1к8 дробящий; Универсальное (1к10)',
    damage: {
      cubeType: 8,
      cubeCount: 1,
    },
    cost: 1500,
    damageType: 'bludgeoning',
    weight: 2,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'boevoi` topor',
    name: 'Боевой топор',
    nameEn: '',
    description: 'Урон 1к8 рубящий; Универсальное (1к10)',
    damage: {
      cubeType: 8,
      cubeCount: 1,
    },
    cost: 1000,
    damageType: 'slashing',
    weight: 4,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'glefa',
    name: 'Глефа',
    nameEn: '',
    description: 'Урон 1к10 рубящий; Двуручное, досягаемость, тяжёлое',
    damage: {
      cubeType: 10,
      cubeCount: 1,
    },
    isTwoHanded: true,
    isReach: true,
    isHeavy: true,
    cost: 2000,
    damageType: 'slashing',
    weight: 6,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'dvuruchny`i` mech',
    name: 'Двуручный меч',
    nameEn: '',
    description: 'Урон 2к6 рубящий; Двуручное, тяжёлое',
    damage: {
      cubeType: 6,
      cubeCount: 2,
    },
    isTwoHanded: true,
    isHeavy: true,
    cost: 5000,
    damageType: 'slashing',
    weight: 6,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'dlinnoe kop`yo',
    name: 'Длинное копьё',
    nameEn: '',
    description: 'Урон 1к12 колющий; Досягаемость, особое. Вы совершаете с помехой атаки длинным копьём по существам, находящимся в пределах 5 футов от вас. Кроме того, если вы не находитесь верхом, длинное копьё используется двумя руками.',
    damage: {
      cubeType: 12,
      cubeCount: 1,
    },
    isReach: true,
    isSpecial: true,
    cost: 1000,
    damageType: 'piercing',
    weight: 6,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'dlinny`i` mech',
    name: 'Длинный меч',
    nameEn: '',
    description: 'Урон 1к8 рубящий; Универсальное (1к10)',
    damage: {
      cubeType: 8,
      cubeCount: 1,
    },
    cost: 1500,
    damageType: 'slashing',
    weight: 3,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'knut',
    name: 'Кнут',
    nameEn: '',
    description: 'Урон 1к4 рубящий; Досягаемость, фехтовальное',
    damage: {
      cubeType: 4,
      cubeCount: 1,
    },
    isFinesse: true,
    isReach: true,
    cost: 200,
    damageType: 'slashing',
    weight: 3,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'korotkii` mech',
    name: 'Короткий меч',
    nameEn: 'Shortsword',
    description: 'Урон 1к6 колющий; Лёгкое, фехтовальное',
    damage: {
      cubeType: 6,
      cubeCount: 1,
    },
    isLight: true,
    isFinesse: true,
    cost: 1000,
    damageType: 'piercing',
    weight: 2,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'molot',
    name: 'Молот',
    nameEn: '',
    description: 'Урон 2к6 колющий; Двуручное, тяжёлое',
    damage: {
      cubeType: 6,
      cubeCount: 2,
    },
    isTwoHanded: true,
    isHeavy: true,
    cost: 1000,
    damageType: 'piercing',
    weight: 10,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'morgenshtern',
    name: 'Моргенштерн',
    nameEn: '',
    description: 'Урон 1к8 колющий',
    damage: {
      cubeType: 8,
      cubeCount: 1,
    },
    cost: 1500,
    damageType: 'piercing',
    weight: 4,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'pika',
    name: 'Пика',
    nameEn: '',
    description: 'Урон 1к10 колющий; Двуручное, досягаемость, тяжёлое',
    damage: {
      cubeType: 10,
      cubeCount: 1,
    },
    isTwoHanded: true,
    isHeavy: true,
    isReach: true,
    cost: 500,
    damageType: 'piercing',
    weight: 18,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'rapira',
    name: 'Рапира',
    nameEn: '',
    description: 'Урон 1к8 колющий; Фехтовальное',
    damage: {
      cubeType: 8,
      cubeCount: 1,
    },
    isFinesse: true,
    cost: 2500,
    damageType: 'piercing',
    weight: 2,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'sekira',
    name: 'Секира',
    nameEn: '',
    description: 'Урон 1к12 колющий; Двуручное, тяжёлое',
    damage: {
      cubeType: 12,
      cubeCount: 1,
    },
    isTwoHanded: true,
    isHeavy: true,
    cost: 3000,
    damageType: 'piercing',
    weight: 7,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'skimitar',
    name: 'Скимитар',
    nameEn: '',
    description: 'Урон 1к6 колющий; Лёгкое, фехтовальное',
    damage: {
      cubeType: 6,
      cubeCount: 1,
    },
    isLight: true,
    isFinesse: true,
    cost: 2500,
    damageType: 'piercing',
    weight: 3,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'trezubetc',
    name: 'Трезубец',
    nameEn: '',
    description: 'Урон 1к6 колющий; Метательное (дис. 20/60), универсальное (1к8)',
    damage: {
      cubeType: 6,
      cubeCount: 1,
    },
    range: {
      normal: 20,
      max: 60,
    },
    isThrown: true,
    cost: 500,
    damageType: 'piercing',
    weight: 4,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'tsep',
    name: 'Цеп',
    nameEn: '',
    description: 'Урон 1к8 дробящий',
    damage: {
      cubeType: 8,
      cubeCount: 1,
    },
    cost: 1000,
    damageType: 'bludgeoning',
    weight: 2,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское рукопашное оружие',
  },
  {
    id: 'arbalet, ruchnoi',
    name: 'Арбалет, ручной',
    nameEn: '',
    description: 'Урон 1к6 колющий; Боеприпас (дис. 30/120), лёгкое, перезарядка',
    damage: {
      cubeType: 6,
      cubeCount: 1,
    },
    range: {
      normal: 30,
      max: 120,
    },
    isLight: true,
    isReloading: true,
    needAmmo: true,
    cost: 7500,
    damageType: 'piercing',
    weight: 3,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское дальнобойное оружие',
  },
  {
    id: 'arbalet, tiazhyoly`i',
    name: 'Арбалет, тяжёлый',
    nameEn: '',
    description: 'Урон 1к10 колющий; Боеприпас (дис. 100/400), двуручное, перезарядка, тяжёлое',
    damage: {
      cubeType: 10,
      cubeCount: 1,
    },
    range: {
      normal: 100,
      max: 400,
    },
    isReloading: true,
    needAmmo: true,
    isTwoHanded: true,
    isHeavy: true,
    cost: 5000,
    damageType: 'piercing',
    weight: 18,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское дальнобойное оружие',
  },
  {
    id: 'dlinny`i` luk',
    name: 'Длинный лук',
    nameEn: 'Longbow',
    description: 'Урон 1к8 колющий; Боеприпас (дис. 150/600), двуручное, тяжёлое',
    damage: {
      cubeType: 8,
      cubeCount: 1,
    },
    range: {
      normal: 150,
      max: 600,
    },
    needAmmo: true,
    isTwoHanded: true,
    isHeavy: true,
    cost: 5000,
    damageType: 'piercing',
    weight: 2,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское дальнобойное оружие',
  },
  {
    id: 'duhovaia trubka',
    name: 'Духовая трубка',
    nameEn: '',
    description: 'Урон 1 колющий; Боеприпас (дис. 25/100), перезарядка',
    damage: {
      cubeType: 0,
      cubeCount: 0,
      cubeBonus: 1,
    },
    range: {
      normal: 25,
      max: 100,
    },
    isReloading: true,
    needAmmo: true,
    cost: 1000,
    damageType: 'piercing',
    weight: 1,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское дальнобойное оружие',
  },
  {
    id: 'set',
    name: 'Сеть',
    nameEn: 'Net',
    description: 'Метательное (дис. 5/15), особое. Существа Большого и меньшего размеров, по которым попала атака сетью, становятся опутанными, пока не высвободятся. Сеть не оказывает эффекта на бесформенных существ и тех, чей размер Огромный или ещё больше. Существо может действием совершить проверку Силы со Сл 10, чтобы высвободиться самому или освободить другое существо, находящееся в пределах его досягаемости. Причинение сети 5 единиц рубящего урона (КД 10) тоже освобождает существо, не причиняя ему вреда, оканчивая эффект и уничтожая сеть.\nЕсли вы действием, бонусным действием или реакцией совершаете атаку сетью, вы можете совершить только одну атаку, вне зависимости от количества положенных атак.',
    range: {
      normal: 5,
      max: 15,
    },
    isThrown: true,
    isSpecial: true,
    cost: 100,
    weight: 3,
    source: 'PHB:149',
    category: 'Оружие',
    subcategory: 'Воинское дальнобойное оружие',
  },
  {
    id: 'abak',
    name: 'Абак',
    nameEn: 'Abacus',
    cost: 200,
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'alhimicheskii` ogon',
    name: 'Алхимический огонь',
    nameEn: 'Alchemist\'s Fire',
    description: 'Эта вязкая и клейкая жидкость воспламеняется при контакте с воздухом. Вы можете действием метнуть фляжку на расстояние до 20 фт, разбив её от удара. Совершите дальнобойную атаку по существу или предмету, считая алхимический огонь импровизированным оружием. При попадании цель получает урон огнём 1к4 в начале каждого своего хода. Существо может окончить этот урон, потратив действие на тушение пламени, и совершив проверку Ловкости со Сл 10.',
    damage: {
      cubeType: 4,
      cubeCount: 1,
    },
    range: {
      normal: 20,
      max: 20,
    },
    cost: 5000,
    damageType: 'fire',
    saveThrow: {
      type: 'dex',
      dc: 10,
    },
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Расходники',
  },
  {
    id: 'blok i lebyodka',
    name: 'Блок и лебёдка',
    nameEn: 'Block and tackle',
    description: 'Набор блоков и тросов с крюками для подвешивания предметов. Блок и лебёдка позволяют вам поднять в четыре раза больше, чем обычно.',
    cost: 100,
    weight: 5,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'arbaletny`e bolty',
    name: 'Арбалетные болты',
    nameEn: '',
    description: '20 шт.',
    cost: 100,
    weight: 1.5,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Боеприпасы',
  },
  {
    id: 'igly` dlia trubki',
    name: 'Иглы для трубки',
    nameEn: '',
    description: '50 шт.',
    cost: 100,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Боеприпасы',
  },
  {
    id: 'snariady` dlia prashchi',
    name: 'Снаряды для пращи',
    nameEn: '',
    description: '20 шт.',
    cost: 4,
    weight: 1.5,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Боеприпасы',
  },
  {
    id: 'strely',
    name: 'Стрелы',
    nameEn: '',
    description: '20 шт.',
    cost: 100,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Боеприпасы',
  },
  {
    id: 'bochka',
    name: 'Бочка',
    nameEn: 'Barrel',
    description: '40 галлонов, 4 кубических фута',
    cost: 200,
    weight: 70,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'bumaga',
    name: 'Бумага',
    nameEn: '',
    description: '1 лист',
    cost: 20,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'burdiuk',
    name: 'Бурдюк',
    nameEn: '',
    description: '4 пинты',
    cost: 20,
    weight: 5,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'buty`lka, stecliannaia',
    name: 'Бутылка, стеклянная',
    nameEn: '',
    description: '1,5 пинты',
    cost: 200,
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'vedro',
    name: 'Ведро',
    nameEn: 'Bucket',
    description: '3 галлона, ½ фт³',
    cost: 5,
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'veryovka pen`kovaia',
    name: 'Верёвка пеньковая',
    nameEn: '',
    description: '50 фт. У верёвки 2 хита, и её можно порвать проверкой Силы со Сл 17',
    cost: 100,
    weight: 10,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'veryovka shyolkovaia',
    name: 'Верёвка шёлковая',
    nameEn: '',
    description: '50 фт. У верёвки 2 хита, и её можно порвать проверкой Силы со Сл 17',
    cost: 1000,
    weight: 5,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'vesy`, torgovy`e',
    name: 'Весы, торговые',
    nameEn: '',
    description: 'В набор входят рычажные весы, чашки и набор грузиков на 2 фунта. С их помощью можно точно измерять вес небольших предметов, таких как драгоценные металлы или товары.',
    cost: 500,
    weight: 3,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'vosk',
    name: 'Воск',
    nameEn: '',
    cost: 50,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'gorshok, zhelezny`i',
    name: 'Горшок, железный',
    nameEn: '',
    description: '1 галлон',
    cost: 200,
    weight: 10,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'grafin',
    name: 'Графин',
    nameEn: '',
    description: '1 галлон',
    cost: 2,
    weight: 4,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'duhi',
    name: 'Духи',
    nameEn: '',
    description: 'флакон',
    cost: 500,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'zamok',
    name: 'Замок',
    nameEn: '',
    description: 'Вместе с замком идёт и ключ. Без ключа существо, владеющее воровскими инструментами, может вскрыть замок успешной проверкой Ловкости со Сл 15. Мастер может решить, что есть более качественные замки, стоящие больше.',
    cost: 1000,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'zel`e lecheniia',
    name: 'Зелье лечения',
    nameEn: '',
    description: 'Существо, выпившее магическую красную жидкость из этого флакона, восстанавливает 2к4 + 2 хита. Зелье выпивается или заливается в рот другому действием.',
    cost: 5000,
    weight: 0.5,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'zerkalo, stal`noe',
    name: 'Зеркало, стальное',
    nameEn: '',
    cost: 500,
    weight: 0.5,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kaltropy',
    name: 'Калтропы',
    nameEn: 'Caltrops',
    description: '20 штук в сумке. Вы можете действием рассыпать сумку калтропов по площади в 5 × 5 фт. Все существа, входящие в эту область, должны преуспеть в спасброске Ловкости со Сл 15, иначе они останавливаются и получают колющий урон 1. Пока это существо не восстановит как минимум 1 хит, его скорость ходьбы уменьшена на 10 фт. Существо, перемещающееся по этой области с уменьшенной вдвое скоростью, не обязано совершать спасбросок.',
    cost: 100,
    damageType: 'piercing',
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kandaly',
    name: 'Кандалы',
    nameEn: '',
    description: 'Эти металлические оковы удерживают существ Маленького и Среднего размера. Для того чтобы сбежать из кандалов, требуется успешная проверка Ловкости со Сл 20. Для того чтобы их сломать, требуется проверка Силы со Сл 20. Каждый набор кандалов идёт с одним ключом. Без ключа существо, владеющее воровскими инструментами, может вскрыть замок кандалов успешной проверкой Ловкости со Сл 15. У кандалов 15 хитов.',
    cost: 200,
    weight: 6,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kislota',
    name: 'Кислота',
    nameEn: 'Acid',
    description: 'Флакон. Вы можете действием выплеснуть содержимое этого сосуда на существо, находящееся в пределах 5 фт от вас, или метнуть сосуд на расстояние до 20 фт, чтобы он разбился от удара. В любом случае совершите дальнобойную атаку против существа или предмета, считая кислоту импровизированным оружием. При попадании цель получает урон кислотой 2к6.',
    damage: {
      cubeType: 6,
      cubeCount: 2,
    },
    range: {
      normal: 20,
      max: 20,
    },
    cost: 2500,
    damageType: 'acid',
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kniga',
    name: 'Книга',
    nameEn: 'Book',
    description: 'В книге могут быть стихи, документальные сведения, информация о чём-либо, диаграммы и заметки о гномьих приспособлениях, или что угодно другое, представленное текстом и картинками.',
    cost: 2500,
    weight: 5,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kniga zaclinanii',
    name: 'Книга заклинаний',
    nameEn: '',
    description: 'Книги заклинаний очень важны для волшебников. Это переплетённые кожей тома, содержащие 100 пустых пергаментных страниц, на которых можно записывать заклинания.',
    cost: 5000,
    weight: 3,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kolokol`chik',
    name: 'Колокольчик',
    nameEn: 'Bell',
    cost: 100,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kolchan',
    name: 'Колчан',
    nameEn: '',
    description: 'В колчан помещается 20 стрел.',
    cost: 100,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kol`tco-pechatka',
    name: 'Кольцо-печатка',
    nameEn: '',
    cost: 500,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'komplekt dlia lazaniia',
    name: 'Комплект для лазания',
    nameEn: 'Climber\'s kit',
    description: 'В набор для лазания входят шлямбуры, накладные подошвы, перчатки и страховочная привязь. Вы можете действием использовать набор для лазания, чтобы закрепиться на высоте; если вы делаете это, вы не можете упасть более чем на 25 фт от того места, где закрепились, но и не можете подняться выше 25 фт от этого места, не открепившись.',
    cost: 2500,
    weight: 12,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'komplekt dlia ry`balki',
    name: 'Комплект для рыбалки',
    nameEn: '',
    description: 'В этот набор входит удилище, шёлковая леска, пробковый поплавок, стальные крючки, свинцовые грузила, приманки из ниток и мелкоячеистая сеть.',
    cost: 100,
    weight: 4,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'komplekt tcelitelia',
    name: 'Комплект целителя',
    nameEn: '',
    description: 'Это кожаный кошель с бинтами, мазями и шинами. Набор годится для 10 использований. Вы можете действием потратить одно использование набора для стабилизации существа, у которого 0 хитов, не совершая проверку Мудрости (Медицина).',
    cost: 500,
    weight: 3,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kontei`ner dlia arbaletny`kh boltov',
    name: 'Контейнер для арбалетных болтов',
    nameEn: 'Crossbow bolt case',
    description: 'В этот деревянный контейнер помещаются 20 арбалетных болтов.',
    cost: 100,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kontei`ner dlia kart i svitkov',
    name: 'Контейнер для карт и свитков',
    nameEn: '',
    description: 'В этом цилиндрическом кожаном тубусе может храниться до десяти скрученных листов бумаги или пять скрученных листов пергамента.',
    cost: 100,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'korzina',
    name: 'Корзина',
    nameEn: '',
    description: '2 фт³/40 фунтов',
    cost: 40,
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'koshel',
    name: 'Кошель',
    nameEn: '',
    description: '0,2 фт³/6 фунтов. В кожаном или тканевом кошеле поместится 20 снарядов для пращи или 50 иголок для духовой трубки, а также другие вещи.',
    cost: 50,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kriuk-koshka',
    name: 'Крюк-кошка',
    nameEn: '',
    cost: 200,
    weight: 4,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'kuvshin',
    name: 'Кувшин',
    nameEn: '',
    description: '1 галлон',
    cost: 2,
    weight: 4,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'lampa',
    name: 'Лампа',
    nameEn: '',
    description: 'Лампа испускает яркий свет в пределах 15 фт и тусклый свет в пределах ещё 30 фт. Зажжённая лампа горит 6 часов от одной фляги (1 пинта) масла.',
    range: {
      normal: 15,
      max: 45,
    },
    cost: 50,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'lestneytca',
    name: 'Лестница',
    nameEn: '',
    description: '10 фт',
    cost: 10,
    weight: 25,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'lomik',
    name: 'Ломик',
    nameEn: 'Crowbar',
    description: 'Использование ломика позволяет совершать проверки Силы с преимуществом, если рычаг должен помочь.',
    cost: 200,
    weight: 5,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'lopata',
    name: 'Лопата',
    nameEn: '',
    description: '',
    cost: 200,
    weight: 5,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'volshebnaia palochka',
    name: 'Волшебная палочка',
    nameEn: '',
    description: 'Это особый предмет, созданный для проведения тайных заклинаний. Волшебники, колдуны и чародеи могут использовать эти предметы в качестве фокусировки для заклинаний, как описано в главе 10.',
    cost: 1000,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Магическая фокусировка',
  },
  {
    id: 'zhezl',
    name: 'Жезл',
    nameEn: '',
    description: 'Это особый предмет, созданный для проведения тайных заклинаний. Волшебники, колдуны и чародеи могут использовать эти предметы в качестве фокусировки для заклинаний, как описано в главе 10.',
    cost: 1000,
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Магическая фокусировка',
  },
  {
    id: 'kristal',
    name: 'Кристал',
    nameEn: 'Crystal',
    description: 'Это особый предмет, созданный для проведения тайных заклинаний. Волшебники, колдуны и чародеи могут использовать эти предметы в качестве фокусировки для заклинаний, как описано в главе 10.',
    cost: 1000,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Магическая фокусировка',
  },
  {
    id: 'posokh',
    name: 'Посох',
    nameEn: '',
    description: 'Это особый предмет, созданный для проведения тайных заклинаний. Волшебники, колдуны и чародеи могут использовать эти предметы в качестве фокусировки для заклинаний, как описано в главе 10.',
    cost: 500,
    weight: 4,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Магическая фокусировка',
  },
  {
    id: 'sfera',
    name: 'Сфера',
    nameEn: '',
    description: 'Это особый предмет, созданный для проведения тайных заклинаний. Волшебники, колдуны и чародеи могут использовать эти предметы в качестве фокусировки для заклинаний, как описано в главе 10.',
    cost: 2000,
    weight: 3,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Магическая фокусировка',
  },
  {
    id: 'maslo',
    name: 'Масло',
    nameEn: '',
    description: 'Фляга. Обычно масло продаётся в глиняных флягах по 1 пинте (0,5 литра). Вы можете действием облить маслом из фляги существо, находящееся в пределах 5 фт, или кинуть её на 20 фт, ломая при ударе. Совершите дальнобойную атаку по целевому существу или предмету, считая масло импровизированным оружием. При попадании цель покрывается маслом. Если цель получает урон огнём, пока масло не высохло (1 минута), она получает дополнительный урон огнём 5 от горящего масла. Вы можете также вылить фляжку масла на землю, покрыв площадь 5 × 5 фт, при условии, что пол ровный. Если теперь масло поджечь, оно горит 2 раунда и причиняет урон огнём 5 всем существам, входящим в эту область или оканчивающим в ней ход. Существо может получить этот урон только один раз за ход.',
    cost: 10,
    damage: {
      cubeBonus: 5,
    },
    range: {
      normal: 20,
      max: 20,
    },
    damageType: 'fire',
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'mel',
    name: 'Мел',
    nameEn: 'Chalk',
    description: '1 кусочек',
    cost: 1,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'metallicheskie shariki',
    name: 'Металлические шарики',
    nameEn: '',
    description: 'В сумке 1000 шт. Вы можете действием рассыпать из этого мешка крохотные металлические шарики, покрыв площадь 10 × 10 фт. Существа, перемещающиеся по этой области, должны преуспеть в спасброске Ловкости со Сл 10, иначе они падают ничком. Существо, перемещающееся по этой области с уменьшенной вдвое скоростью, не обязано совершать спасбросок',
    cost: 100,
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'meshok',
    name: 'Мешок',
    nameEn: '',
    description: '1 кубический фут/30 фунтов',
    cost: 1,
    weight: 0.5,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'meshochek s komponentami',
    name: 'Мешочек с компонентами',
    nameEn: '',
    description: 'Мешочек с компонентами это маленький водонепроницаемый кожаный поясной кошель с отделениями для хранения материальных компонентов и других особых предметов, нужных для накладывания заклинаний, если только у этих компонентов не указана стоимость (смотрите описание заклинания).',
    cost: 2500,
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'molot, kuznechny`i',
    name: 'Молот, кузнечный',
    nameEn: '',
    cost: 200,
    weight: 10,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'molotok',
    name: 'Молоток',
    nameEn: '',
    cost: 100,
    weight: 3,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'my`lo',
    name: 'Мыло',
    nameEn: '',
    cost: 2,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'dorozhnaia odezhda',
    name: 'Дорожная одежда',
    nameEn: '',
    cost: 200,
    weight: 4,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Одежда',
  },
  {
    id: 'kostium',
    name: 'Костюм',
    nameEn: 'Costume clothes',
    cost: 500,
    weight: 4,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Одежда',
  },
  {
    id: 'oby`chnaia odezhda',
    name: 'Обычная одежда',
    nameEn: 'Common clothes',
    cost: 50,
    weight: 3,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Одежда',
  },
  {
    id: 'otlichnaia odezhda',
    name: 'Отличная одежда',
    nameEn: '',
    cost: 1500,
    weight: 6,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Одежда',
  },
  {
    id: 'odeialo',
    name: 'Одеяло',
    nameEn: 'Blanket',
    cost: 50,
    weight: 3,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'ohotneychii` kapkan',
    name: 'Охотничий капкан',
    nameEn: '',
    description: 'Если вы действием установите эту ловушку, она образует стальное кольцо с зазубренными краями, которая захлопывается, когда в её центр наступает существо. Капкан привязывается толстой цепью к неподвижному предмету, такому как дерево или колышек, вбитый в землю. Существо, наступившее в центр, должно преуспеть в спасброске Ловкости со Сл 13, иначе оно получает колющий урон 1к4 и прекращает перемещение. Впоследствии, пока существо не высвободится из ловушки, его перемещения ограничены длиной цепи (обычно 3 фута). Любое существо может действием совершить проверку Силы со Сл 13, чтобы высвободить себя или другое существо, находящееся в пределах досягаемости. Каждая проваленная проверка причиняет пойманному существу колющий урон 1.',
    damage: {
      cubeType: 4,
      cubeCount: 1,
    },
    cost: 500,
    damageType: 'piercing',
    weight: 25,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'palatka',
    name: 'Палатка',
    nameEn: '',
    description: 'В палатке, простом парусиновом жилище, могут спать двое.',
    cost: 200,
    weight: 20,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'pergament',
    name: 'Пергамент',
    nameEn: '',
    description: '1 лист',
    cost: 10,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'pesochny`e chasy',
    name: 'Песочные часы',
    nameEn: '',
    cost: 2500,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'pischee pero',
    name: 'Писчее перо',
    nameEn: '',
    cost: 2,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'podzornaia truba',
    name: 'Подзорная труба',
    nameEn: '',
    description: 'Предметы, на которые смотрят в подзорную трубу, увеличиваются в два раза.',
    cost: 100000,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'protivoiadie',
    name: 'Противоядие',
    nameEn: 'Antitoxin',
    description: 'Флакон. Существо, выпившее жидкость из этого флакона, в течение часа совершает спасброски от яда с преимуществом. Оно не предоставляет преимущества нежити и конструктам.',
    cost: 5000,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'ratcion',
    name: 'Рацион',
    nameEn: '',
    description: 'На 1 день. Рационы состоят из обезвоженной пищи, подходящей для путешествий, включая вяленое мясо, сухофрукты, галеты и орехи.',
    cost: 50,
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'riukzak',
    name: 'Рюкзак',
    nameEn: '',
    description: '1 фт³/30 фунтов',
    cost: 200,
    weight: 5,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'riasa',
    name: 'Ряса',
    nameEn: '',
    cost: 100,
    weight: 4,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'svecha',
    name: 'Свеча',
    nameEn: 'Candle',
    description: 'В течение 1 часа свеча испускает яркий свет в пределах радиуса 5 фт и тусклый свет в пределах ещё 5 фт.',
    range: {
      normal: 5,
      max: 10,
    },
    cost: 1,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'sviataia voda',
    name: 'Святая вода',
    nameEn: '',
    description: 'Вы можете действием облить содержимым этой фляги существо, находящееся в пределах 5 фт, или кинуть флягу на 20 фт, ломая при ударе. Совершите дальнобойную атаку по целевому существу, считая святую воду импровизированным оружием. Если цель — изверг или нежить, она получает урон излучением 2к6.\nЖрец или паладин может создать святую воду, исполнив особый ритуал. Этот ритуал исполняется 1 час, использует толчёное серебро на 25 зм и требует, чтобы заклинатель потратил ячейку заклинаний 1 уровня.',
    damage: {
      cubeType: 6,
      cubeCount: 2,
    },
    range: {
      normal: 20,
      max: 20,
    },
    cost: 2500,
    damageType: 'radiant',
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'amulet',
    name: 'Амулет',
    nameEn: '',
    description: 'Священный символ изображает божество или целый пантеон. Это амулет, изображающий символ божества. Жрец или паладин может использовать священный символ в качестве фокусировки для заклинаний. Для такого использования символа заклинатель должен держать его в руке, носить у всех на виду или нести на щите.',
    cost: 500,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Священный символ',
  },
  {
    id: 'relikvarii',
    name: 'Реликварий',
    nameEn: '',
    description: 'Священный символ изображает божество или целый пантеон. Это крохотная коробочка, в которой хранится священная реликвия. Жрец или паладин может использовать священный символ в качестве фокусировки для заклинаний. Для такого использования символа заклинатель должен держать его в руке, носить у всех на виду или нести на щите.',
    cost: 500,
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Священный символ',
  },
  {
    id: 'e`mblema',
    name: 'Эмблема',
    nameEn: '',
    description: 'Священный символ изображает божество или целый пантеон. Это символ, выгравированный или выложенный камнями в качестве эмблемы на щите. Жрец или паладин может использовать священный символ в качестве фокусировки для заклинаний. Для такого использования символа заклинатель должен держать его в руке, носить у всех на виду или нести на щите.',
    cost: 500,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Священный символ',
  },
  {
    id: 'signal`ny`i` svistok',
    name: 'Сигнальный свисток',
    nameEn: '',
    cost: 5,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'spal`nik',
    name: 'Спальник',
    nameEn: 'Bedroll',
    cost: 100,
    weight: 7,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'stolovy`i` nabor',
    name: 'Столовый набор',
    nameEn: '',
    description: 'В этой небольшой коробке находится чашка и простые столовые приборы. Коробка раскрывается, и одна сторона может использоваться как сковорода, а другая — как тарелка или неглубокая миска.',
    cost: 20,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'sunduk',
    name: 'Сундук',
    nameEn: 'Chest',
    description: '12 фт³/300 фунтов',
    cost: 500,
    weight: 25,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'taran, portativny`i',
    name: 'Таран, портативный',
    nameEn: '',
    description: 'Вы можете вышибать портативным тараном двери. Вы получаете бонус +4 к проверкам Силы. Если другой персонаж помогает вам использовать таран, вы совершаете проверку с преимуществом.',
    cost: 400,
    weight: 35,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'tochil`ny`i` kamen',
    name: 'Точильный камень',
    nameEn: '',
    cost: 1,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'trutneytca',
    name: 'Трутница',
    nameEn: '',
    description: 'В этом небольшом контейнере находится кремень, кресало и трут (обычно это сухая тряпка, вымоченная в масле), используемые для разжигания огня. Использование его для разжигания факела — или чего-нибудь другого, легковоспламеняющегося — требует одного действия. Разжигание другого огня требует 1 минуты.',
    cost: 50,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'uvelichitel`noe steclo',
    name: 'Увеличительное стекло',
    nameEn: '',
    description: 'Эта линза позволяет разглядывать маленькие предметы. Линзу также можно использовать для замены кремня и кресала. Разжигание огня увеличительным стеклом требует света, яркого как свет солнца, трута для розжига и примерно 5 минут. Увеличительное стекло позволяет совершать с преимуществом проверки характеристик, сделанных для оценки или исследования мелких и высокодетализированных предметов.',
    cost: 10000,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'fakel',
    name: 'Факел',
    nameEn: '',
    description: 'Факел горит 1 час, испуская яркий свет в пределах 20 фт и тусклый свет в пределах ещё 20 фт. Если вы совершаете рукопашную атаку горящим факелом и попадаете, он причиняет урон огнём 1.',
    damage: {
      cubeBonus: 1,
    },
    range: {
      normal: 20,
      max: 40,
    },
    cost: 1,
    damageType: 'fire',
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'flakon',
    name: 'Флакон',
    nameEn: '',
    description: '4 унции',
    cost: 100,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'bol`shaia kruzhka',
    name: 'Большая кружка',
    nameEn: '',
    description: '1 пинта',
    cost: 2,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'fliaga',
    name: 'Фляга',
    nameEn: '',
    description: '1 пинта',
    cost: 2,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'vetochka omely',
    name: 'Веточка омелы',
    nameEn: '',
    description: 'Друид может использовать этот предмет в качестве фокусировки для заклинаний.',
    cost: 100,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Фокусировка друидов',
  },
  {
    id: 'vetochka paduba',
    name: 'Веточка падуба',
    nameEn: '',
    description: 'Друид может использовать этот предмет в качестве фокусировки для заклинаний.',
    cost: 100,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Фокусировка друидов',
  },
  {
    id: 'dereviannaia palochka',
    name: 'Деревянная палочка',
    nameEn: '',
    description: 'Палочка из тиса или другого дерева. Друид может использовать этот предмет в качестве фокусировки для заклинаний.',
    cost: 1000,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Фокусировка друидов',
  },
  {
    id: 'derevianny`i` skipetr',
    name: 'Деревянный скипетр',
    nameEn: '',
    description: 'Скипетр из тиса или другого дерева. Друид может использовать этот предмет в качестве фокусировки для заклинаний.',
    cost: 1000,
    weight: 1,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Фокусировка друидов',
  },
  {
    id: 'derevianny`i` posokh',
    name: 'Деревянный посох',
    nameEn: '',
    description: 'Посох, созданный из живого дерева. Друид может использовать этот предмет в качестве фокусировки для заклинаний.',
    cost: 500,
    weight: 4,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Фокусировка друидов',
  },
  {
    id: 'totem',
    name: 'Тотем',
    nameEn: '',
    description: 'Тотем с перьями, мехом, костями и зубами священных животных. Друид может использовать этот предмет в качестве фокусировки для заклинаний.',
    cost: 100,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Фокусировка друидов',
  },
  {
    id: 'fonar`, zakry`ty`i',
    name: 'Фонарь, закрытый',
    nameEn: '',
    description: 'Закрытый фонарь испускает яркий свет в пределах 30 фт и тусклый свет в  пределах ещё 30 фт. Зажжённый фонарь горит 6 часов от одной фляги (1 пинта) масла. Вы можете действием опустить козырёк, уменьшив освещение до тусклого света в пределах 5 фт.',
    range: {
      normal: 30,
      max: 60,
    },
    cost: 500,
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'fonar`, napravlenny`i',
    name: 'Фонарь, направленный',
    nameEn: 'Bullseye lantern',
    description: 'Направленный фонарь испускает яркий свет 60-фтым конусом и тусклый свет в пределах ещё 60 фт. Зажжённый фонарь горит 6 часов от одной фляги (1 пинта) масла.',
    range: {
      normal: 60,
      max: 120,
    },
    cost: 1000,
    weight: 2,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'chain',
    name: 'Цепь',
    nameEn: 'Chain',
    description: 'Длина 10 фт. У цепи 10 хитов. Её можно порвать успешной проверкой Силы со Сл 20.',
    length: 10,
    hp: 10,
    cost: 500,
    saveThrow: {
      type: 'str',
      dc: 20,
    },
    weight: 10,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'chernila',
    name: 'Чернила',
    nameEn: '',
    description: 'Бутылочка, 1 унция',
    cost: 1000,
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'shest',
    name: 'Шест',
    nameEn: '',
    description: 'Длина 10 фт',
    cost: 5,
    weight: 7,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'shipy` zhelezny`e',
    name: 'Шипы железные',
    nameEn: '',
    description: '10 штук',
    cost: 100,
    weight: 5,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'shliambur',
    name: 'Шлямбур',
    nameEn: '',
    cost: 5,
    weight: 0.25,
    source: 'PHB:150',
    category: 'Снаряжение',
  },
  {
    id: 'iad, prostoi',
    name: 'Яд, простой',
    nameEn: 'Basic Poison',
    description: 'Вы можете покрыть ядом из этого флакона одно рубящее или колющее оружие или три боеприпаса. Наносится яд одним действием. Существо, по которому попадёт отравленное оружие или боеприпас, должно совершить спасбросок Телосложения со Сл 10, получая в случае провала урон ядом 1к4. Нанесённый яд эффективен 1 минуту, после чего высыхает.',
    damage: {
      cubeType: 4,
      cubeCount: 1,
    },
    saveThrow: {
      type: 'con',
      dc: 10,
    },
    cost: 10000,
    damageType: 'poison',
    poisonType: 'injury',
    weight: 0,
    source: 'PHB:150',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'nabor artista',
    name: 'Набор артиста',
    nameEn: '',
    description: 'Включает рюкзак, спальник, 2 костюма, 5 свечек, рационы на 5 дней, бурдюк и набор для грима',
    cost: 4000,
    weight: 35,
    source: 'PHB:151',
    category: 'Снаряжение',
    subcategory: 'Набор',
  },
  {
    id: 'nabor vzlomshchika',
    name: 'Набор взломщика',
    nameEn: '',
    description: 'Включает рюкзак, сумку с 1 000 металлических шариков, 10 фт лески, колокольчик, 5 свечек, ломик, молоток, 10 шлямбуров, закрытый фонарь, 2 фляги масла, рационы на 5 дней, трутницу и бурдюк. В набор также входит 50-футовая пеньковая верёвка, закреплённая сбоку.',
    cost: 1600,
    weight: 39,
    source: 'PHB:151',
    category: 'Снаряжение',
    subcategory: 'Набор',
  },
  {
    id: 'nabor diplomata',
    name: 'Набор дипломата',
    nameEn: '',
    description: 'Включает сундук, 2 контейнера для карт и свитков, комплект отличной одежды, бутылочку чернил, писчее перо, лампу, 2 фляги масла, 5 листов бумаги, флакон духов, воск и мыло.',
    cost: 3900,
    weight: 36,
    source: 'PHB:151',
    category: 'Снаряжение',
    subcategory: 'Набор',
  },
  {
    id: 'nabor issledovatelia podzemelii',
    name: 'Набор исследователя подземелий',
    nameEn: '',
    description: 'Включает рюкзак, ломик, молоток, 10 шлямбуров, 10 факелов, трутницу, рационы на 10 дней и бурдюк. В набор также входит 50-футовая пеньковая верёвка, закреплённая сбоку.',
    cost: 1200,
    weight: 43,
    source: 'PHB:151',
    category: 'Снаряжение',
    subcategory: 'Набор',
  },
  {
    id: 'nabor puteshestvennika',
    name: 'Набор путешественника',
    nameEn: '',
    description: 'Включает рюкзак, спальник, столовый набор, трутницу, 10 факелов, рационы на 10 дней и бурдюк. В набор также входит 50-футовая пеньковая верёвка, закреплённая сбоку.',
    cost: 1000,
    weight: 59,
    source: 'PHB:151',
    category: 'Снаряжение',
    subcategory: 'Набор',
  },
  {
    id: 'nabor sviashchennika',
    name: 'Набор священника',
    nameEn: '',
    description: 'Включает рюкзак, одеяло, 10 свечек, трутницу, коробку для пожертвований, 2 упаковки благовоний, кадило, облачение, рационы на 2 дня и бурдюк.',
    cost: 1900,
    weight: 22,
    source: 'PHB:151',
    category: 'Снаряжение',
    subcategory: 'Набор',
  },
  {
    id: 'nabor uchyonogo',
    name: 'Набор учёного',
    nameEn: '',
    description: 'Включает рюкзак, научную книгу, бутылочку чернил, писчее перо, 10 листов пергамента, небольшую сумочку с песком и небольшой нож.',
    cost: 4000,
    weight: 11,
    source: 'PHB:151',
    category: 'Снаряжение',
    subcategory: 'Набор',
  },
  {
    id: 'vorovskie instrumenty',
    name: 'Воровские инструменты',
    nameEn: '',
    description: 'В этот набор инструментов входят небольшой напильник, набор отмычек, небольшое зеркальце на длинной ручке, ножницы и пара щипчиков. Владение этими инструментами позволяет добавлять бонус мастерства ко всем проверкам характеристик, сделанным для отключения ловушек и взлома замков.',
    cost: 2500,
    weight: 1,
    source: 'PHB:154',
    category: 'Инструменты',
  },
  {
    id: 'drakon`i shakhmaty',
    name: 'Драконьи шахматы',
    nameEn: '',
    description: 'Игры могут состоять из разных предметов, включая кости и колоды карт. В таблице указаны примеры игр, но есть и другие наборы. Если вы владеете игровым набором, вы можете добавлять бонус мастерства к проверкам характеристик, совершаемым во время игры. Для каждой игры требуется отдельное владение.',
    cost: 100,
    weight: 0.5,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Игровой набор',
  },
  {
    id: 'karty',
    name: 'Карты',
    nameEn: '',
    description: 'Игры могут состоять из разных предметов, включая кости и колоды карт. В таблице указаны примеры игр, но есть и другие наборы. Если вы владеете игровым набором, вы можете добавлять бонус мастерства к проверкам характеристик, совершаемым во время игры. Для каждой игры требуется отдельное владение.',
    cost: 50,
    weight: 0,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Игровой набор',
  },
  {
    id: 'kosti',
    name: 'Кости',
    nameEn: 'Dice set',
    description: 'Игры могут состоять из разных предметов, включая кости и колоды карт. В таблице указаны примеры игр, но есть и другие наборы. Если вы владеете игровым набором, вы можете добавлять бонус мастерства к проверкам характеристик, совершаемым во время игры. Для каждой игры требуется отдельное владение.',
    cost: 10,
    weight: 0,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Игровой набор',
  },
  {
    id: 'stavka tryokh drakonov',
    name: 'Ставка трёх драконов',
    nameEn: '',
    description: 'Игры могут состоять из разных предметов, включая кости и колоды карт. В таблице указаны примеры игр, но есть и другие наборы. Если вы владеете игровым набором, вы можете добавлять бонус мастерства к проверкам характеристик, совершаемым во время игры. Для каждой игры требуется отдельное владение.',
    cost: 100,
    weight: 0,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Игровой набор',
  },
  {
    id: 'instrumenty` navigatora',
    name: 'Инструменты навигатора',
    nameEn: '',
    description: 'Эти инструменты используются для навигации в море. Владение инструментами навигатора позволяет прокладывать курс корабля и пользоваться морскими картами. Кроме того, эти инструменты позволяют вам добавлять бонус мастерства к проверкам характеристик, совершённым, чтобы не потеряться в море.',
    cost: 2500,
    weight: 2,
    source: 'PHB:154',
    category: 'Инструменты',
  },
  {
    id: 'instrumenty` otravitelia',
    name: 'Инструменты отравителя',
    nameEn: '',
    description: 'В набор отравителя входят флаконы, химикаты и прочее снаряжение, необходимое для создания ядов. Владение этим набором позволяет вам добавлять бонус мастерства к проверкам характеристик, совершённым для создания и использования ядов.',
    cost: 5000,
    weight: 2,
    source: 'PHB:154',
    category: 'Инструменты',
  },
  {
    id: 'instrumenty` alhimika',
    name: 'Инструменты алхимика',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 5000,
    weight: 8,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` gonchara',
    name: 'Инструменты гончара',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 1000,
    weight: 3,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` zhestianshchika',
    name: 'Инструменты жестянщика',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 5000,
    weight: 10,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` kalligrafa',
    name: 'Инструменты каллиграфа',
    nameEn: 'Calligrapher\'s Supplies',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 1000,
    weight: 5,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` kamenshchika',
    name: 'Инструменты каменщика',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 1000,
    weight: 8,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` kartografa',
    name: 'Инструменты картографа',
    nameEn: 'Cartographer\'s Tools',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 1500,
    weight: 6,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` kozhevnika',
    name: 'Инструменты кожевника',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 500,
    weight: 5,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` kuznetca',
    name: 'Инструменты кузнеца',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 2000,
    weight: 8,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` pivovara',
    name: 'Инструменты пивовара',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 2000,
    weight: 9,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` plotneyka',
    name: 'Инструменты плотника',
    nameEn: 'Carpenter\'s Tools',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 800,
    weight: 6,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` povara',
    name: 'Инструменты повара',
    nameEn: 'Cook\'s utensils',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 100,
    weight: 8,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` rezchika po derevu',
    name: 'Инструменты резчика по дереву',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 100,
    weight: 5,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` sapozhnika',
    name: 'Инструменты сапожника',
    nameEn: 'Cobbler\'s Tools',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 500,
    weight: 5,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` stecloduva',
    name: 'Инструменты стеклодува',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 3000,
    weight: 5,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` tkacha',
    name: 'Инструменты ткача',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 100,
    weight: 5,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` hudozhnika',
    name: 'Инструменты художника',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 1000,
    weight: 5,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'instrumenty` iuvelira',
    name: 'Инструменты ювелира',
    nameEn: '',
    description: 'В эти особые наборы входят инструменты, необходимые для ремесла и торговли. Владение инструментами ремесленника позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при использовании инструментов в ремесле.',
    cost: 2500,
    weight: 2,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Инструменты ремесленников',
  },
  {
    id: 'baraban',
    name: 'Барабан',
    nameEn: 'Drum',
    description: 'Если вы владеете определённым музыкальным инструментом, вы можете добавлять бонус мастерства к проверкам характеристик, совершённым во время игры на нём. Бард может использовать музыкальный инструмент в качестве фокусировки для заклинаний.',
    cost: 600,
    weight: 3,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Музыкальные инструменты',
  },
  {
    id: 'viola',
    name: 'Виола',
    nameEn: '',
    description: 'Если вы владеете определённым музыкальным инструментом, вы можете добавлять бонус мастерства к проверкам характеристик, совершённым во время игры на нём. Бард может использовать музыкальный инструмент в качестве фокусировки для заклинаний.',
    cost: 3000,
    weight: 1,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Музыкальные инструменты',
  },
  {
    id: 'voly`nka',
    name: 'Волынка',
    nameEn: '',
    description: 'Если вы владеете определённым музыкальным инструментом, вы можете добавлять бонус мастерства к проверкам характеристик, совершённым во время игры на нём. Бард может использовать музыкальный инструмент в качестве фокусировки для заклинаний.',
    cost: 3000,
    weight: 6,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Музыкальные инструменты',
  },
  {
    id: 'leera',
    name: 'Лира',
    nameEn: '',
    description: 'Если вы владеете определённым музыкальным инструментом, вы можете добавлять бонус мастерства к проверкам характеристик, совершённым во время игры на нём. Бард может использовать музыкальный инструмент в качестве фокусировки для заклинаний.',
    cost: 3000,
    weight: 2,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Музыкальные инструменты',
  },
  {
    id: 'liutnia',
    name: 'Лютня',
    nameEn: '',
    description: 'Если вы владеете определённым музыкальным инструментом, вы можете добавлять бонус мастерства к проверкам характеристик, совершённым во время игры на нём. Бард может использовать музыкальный инструмент в качестве фокусировки для заклинаний.',
    cost: 3500,
    weight: 2,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Музыкальные инструменты',
  },
  {
    id: 'rozhok',
    name: 'Рожок',
    nameEn: '',
    description: 'Если вы владеете определённым музыкальным инструментом, вы можете добавлять бонус мастерства к проверкам характеристик, совершённым во время игры на нём. Бард может использовать музыкальный инструмент в качестве фокусировки для заклинаний.',
    cost: 300,
    weight: 2,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Музыкальные инструменты',
  },
  {
    id: 'svirel',
    name: 'Свирель',
    nameEn: '',
    description: 'Если вы владеете определённым музыкальным инструментом, вы можете добавлять бонус мастерства к проверкам характеристик, совершённым во время игры на нём. Бард может использовать музыкальный инструмент в качестве фокусировки для заклинаний.',
    cost: 1200,
    weight: 2,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Музыкальные инструменты',
  },
  {
    id: 'flei`ta',
    name: 'Флейта',
    nameEn: '',
    description: 'Если вы владеете определённым музыкальным инструментом, вы можете добавлять бонус мастерства к проверкам характеристик, совершённым во время игры на нём. Бард может использовать музыкальный инструмент в качестве фокусировки для заклинаний.',
    cost: 200,
    weight: 1,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Музыкальные инструменты',
  },
  {
    id: 'tcimbaly',
    name: 'Цимбалы',
    nameEn: '',
    description: 'Если вы владеете определённым музыкальным инструментом, вы можете добавлять бонус мастерства к проверкам характеристик, совершённым во время игры на нём. Бард может использовать музыкальный инструмент в качестве фокусировки для заклинаний.',
    cost: 2500,
    weight: 10,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Музыкальные инструменты',
  },
  {
    id: 'shalmei',
    name: 'Шалмей',
    nameEn: '',
    description: 'Если вы владеете определённым музыкальным инструментом, вы можете добавлять бонус мастерства к проверкам характеристик, совершённым во время игры на нём. Бард может использовать музыкальный инструмент в качестве фокусировки для заклинаний.',
    cost: 200,
    weight: 1,
    source: 'PHB:154',
    category: 'Инструменты',
    subcategory: 'Музыкальные инструменты',
  },
  {
    id: 'nabor dlia grima',
    name: 'Набор для грима',
    nameEn: 'Disguise kit',
    description: 'Этот набор косметики, красителей для волос и бутафории позволяет изменять ваш внешний облик. Владение этим набором позволяет добавлять бонус мастерства к проверкам характеристик, совершённым для визуальной маскировки.',
    cost: 2500,
    weight: 3,
    source: 'PHB:154',
    category: 'Инструменты',
  },
  {
    id: 'nabor dlia fal`sifikatcii',
    name: 'Набор для фальсификации',
    nameEn: '',
    description: 'В этой небольшой коробке лежат разные бумаги и пергаменты, ручки и чернила, печати и куски воска, золотая и серебряная фольга, и прочие припасы, необходимые для создания убедительных подделок документов. Владение этим набором позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при создании поддельных документов.',
    cost: 1500,
    weight: 5,
    source: 'PHB:154',
    category: 'Инструменты',
  },
  {
    id: 'nabor travnika',
    name: 'Набор травника',
    nameEn: '',
    description: 'В этот набор входят разнообразные инструменты, такие как ножницы, ступка и пестик, а также мешочки и флаконы, используемые травниками при создании снадобий и зелий. Владение этим набором позволяет добавлять бонус мастерства к проверкам характеристик, совершённым при опознании и использовании трав. Кроме того, владение этим набором требуется для создания противоядия и зелья лечения.',
    cost: 500,
    weight: 3,
    source: 'PHB:154',
    category: 'Инструменты',
  },
  {
    id: 'boevoi` kon',
    name: 'Боевой конь',
    nameEn: '',
    description: 'Скорость 60 фт. Грузоподъёмность 540 фунтов.',
    cost: 40000,
    source: 'PHB:157',
    category: 'Скакуны и другие животные',
  },
  {
    id: 'verbliud',
    name: 'Верблюд',
    nameEn: '',
    description: 'Скорость 50 фт. Грузоподъёмность 480 фунтов.',
    cost: 5000,
    source: 'PHB:157',
    category: 'Скакуны и другие животные',
  },
  {
    id: 'loshad`, ezdovaia',
    name: 'Лошадь, ездовая',
    nameEn: '',
    description: 'Скорость 60 фт. Грузоподъёмность 480 фунтов.',
    cost: 7500,
    source: 'PHB:157',
    category: 'Скакуны и другие животные',
  },
  {
    id: 'loshad`, tiaglovaia',
    name: 'Лошадь, тягловая',
    nameEn: '',
    description: 'Скорость 40 фт. Грузоподъёмность 540 фунтов.',
    cost: 5000,
    source: 'PHB:157',
    category: 'Скакуны и другие животные',
  },
  {
    id: 'mastiff',
    name: 'Мастифф',
    nameEn: '',
    description: 'Скорость 40 фт. Грузоподъёмность 195 фунтов.',
    cost: 2500,
    source: 'PHB:157',
    category: 'Скакуны и другие животные',
  },
  {
    id: 'mul',
    name: 'Мул',
    nameEn: '',
    description: 'Скорость 40 фт. Грузоподъёмность 420 фунтов.',
    cost: 800,
    source: 'PHB:157',
    category: 'Скакуны и другие животные',
  },
  {
    id: 'osyol',
    name: 'Осёл',
    nameEn: '',
    description: 'Скорость 40 фт. Грузоподъёмность 420 фунтов.',
    cost: 800,
    source: 'PHB:157',
    category: 'Скакуны и другие животные',
  },
  {
    id: 'poni',
    name: 'Пони',
    nameEn: '',
    description: 'Скорость 40 фт. Грузоподъёмность 225 фунтов.',
    cost: 3000,
    source: 'PHB:157',
    category: 'Скакуны и другие животные',
  },
  {
    id: 'slon',
    name: 'Слон',
    nameEn: '',
    description: 'Скорость: 40 фт. Грузоподъёмность 1320 фунтов.',
    cost: 20000,
    source: 'PHB:157',
    category: 'Скакуны и другие животные',
  },
  {
    id: 'tritceratops',
    name: 'Трицератопс',
    nameEn: '',
    description: 'Скорость: 50 фт. Грузоподъёмность 1320 фунтов.',
    cost: 50000,
    source: 'PHB:157',
    category: 'Скакуны и другие животные',
  },
  {
    id: 'kareta',
    name: 'Карета',
    nameEn: '',
    cost: 25000,
    weight: 100,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
  },
  {
    id: 'koliaska',
    name: 'Коляска',
    nameEn: '',
    cost: 10000,
    weight: 600,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
  },
  {
    id: 'koniushnia',
    name: 'Конюшня',
    nameEn: '',
    description: 'В день',
    cost: 50,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
  },
  {
    id: 'korm',
    name: 'Корм',
    nameEn: '',
    description: 'В день',
    cost: 5,
    weight: 10,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
  },
  {
    id: 'sani',
    name: 'Сани',
    nameEn: '',
    cost: 2000,
    weight: 300,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
  },
  {
    id: 'sedel`ny`e sumki',
    name: 'Седельные сумки',
    nameEn: '',
    cost: 400,
    weight: 8,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
  },
  {
    id: 'voennoe sedlo',
    name: 'Военное седло',
    nameEn: '',
    cost: 2000,
    weight: 30,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
    subcategory: 'Сёдла',
  },
  {
    id: 'gruzovoe sedlo',
    name: 'Грузовое седло',
    nameEn: '',
    cost: 500,
    weight: 15,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
    subcategory: 'Сёдла',
  },
  {
    id: 'ezdovoe sedlo',
    name: 'Ездовое седло',
    nameEn: '',
    cost: 1000,
    weight: 25,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
    subcategory: 'Сёдла',
  },
  {
    id: 'e`kzoticheskoe sedlo',
    name: 'Экзотическое седло',
    nameEn: '',
    cost: 6000,
    weight: 40,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
    subcategory: 'Сёдла',
  },
  {
    id: 'telega',
    name: 'Телега',
    nameEn: '',
    cost: 1500,
    weight: 200,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
  },
  {
    id: 'upriazh` i uzdechka',
    name: 'Упряжь и уздечка',
    nameEn: '',
    cost: 200,
    weight: 1,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
  },
  {
    id: 'furgon',
    name: 'Фургон',
    nameEn: '',
    cost: 3500,
    weight: 400,
    source: 'PHB:157',
    category: 'Сёдла, упряжь и транспорт',
  },
  {
    id: 'voenny`i` korabl',
    name: 'Военный корабль',
    nameEn: '',
    description: 'Скорость: 2,5 узла',
    cost: 2500000,
    source: 'PHB:157',
    category: 'Водный транспорт',
  },
  {
    id: 'galera',
    name: 'Галера',
    nameEn: '',
    description: 'Скорость: 4 узла',
    cost: 3000000,
    source: 'PHB:157',
    category: 'Водный транспорт',
  },
  {
    id: 'kilevaia lodka',
    name: 'Килевая лодка',
    nameEn: '',
    description: 'Скорость: 1 узел',
    cost: 300000,
    source: 'PHB:157',
    category: 'Водный транспорт',
  },
  {
    id: 'lad`ia',
    name: 'Ладья',
    nameEn: '',
    description: 'Скорость: 3 узла',
    cost: 1000000,
    source: 'PHB:157',
    category: 'Водный транспорт',
  },
  {
    id: 'parusny`i` korabl',
    name: 'Парусный корабль',
    nameEn: '',
    description: 'Скорость: 2 узла',
    cost: 1000000,
    source: 'PHB:157',
    category: 'Водный транспорт',
  },
  {
    id: 'shliupka (vyosel`naia lodka)',
    name: 'Шлюпка (вёсельная лодка)',
    nameEn: '',
    description: 'Скорость: 1,5 узла. Мест: 2',
    cost: 50,
    weight: 100,
    source: 'PHB:157',
    category: 'Водный транспорт',
  },
  {
    id: 'kanoe',
    name: 'Каноэ',
    nameEn: 'Canoe',
    description: 'Скорость: 2 узла. Мест: 6',
    cost: 5000,
    weight: 100,
    source: 'ToA:32',
    category: 'Водный транспорт',
  },
  {
    id: 'pshenitca',
    name: 'Пшеница',
    nameEn: '',
    cost: 1,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'muka',
    name: 'Мука',
    nameEn: '',
    cost: 2,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'kuritca',
    name: 'Курица',
    nameEn: '',
    cost: 2,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'sol',
    name: 'Соль',
    nameEn: '',
    cost: 5,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'zhelezo',
    name: 'Железо',
    nameEn: '',
    description: '',
    cost: 10,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'holst',
    name: 'Холст',
    nameEn: '',
    description: '10 фт²',
    cost: 10,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'med',
    name: 'Медь',
    nameEn: '',
    cost: 50,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'kHlopchatobumazhnaia tkan',
    name: 'Хлопчатобумажная ткань',
    nameEn: '',
    description: '10 фт²',
    cost: 50,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'imbir',
    name: 'Имбирь',
    nameEn: '',
    cost: 100,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'koza',
    name: 'Коза',
    nameEn: '',
    cost: 100,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'koritca',
    name: 'Корица',
    nameEn: '',
    cost: 200,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'peretc',
    name: 'Перец',
    nameEn: '',
    cost: 200,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'ovtca',
    name: 'Овца',
    nameEn: '',
    cost: 200,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'gvozdika',
    name: 'Гвоздика',
    nameEn: '',
    cost: 300,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'svin`ia',
    name: 'Свинья',
    nameEn: '',
    cost: 300,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'serebro',
    name: 'Серебро',
    nameEn: '',
    cost: 500,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'l`nianaia tkan',
    name: 'Льняная ткань',
    nameEn: '',
    description: '10 фт²',
    cost: 300,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'shafran',
    name: 'Шафран',
    nameEn: '',
    cost: 1500,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'vol',
    name: 'Вол',
    nameEn: '',
    cost: 1500,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'zoloto',
    name: 'Золото',
    nameEn: '',
    cost: 5000,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'platina',
    name: 'Платина',
    nameEn: '',
    cost: 50000,
    weight: 1,
    source: 'PHB:157',
    category: 'Товары',
  },
  {
    id: 'sredstvo dlia otpugivaniia nasekomy`kh: maz',
    name: 'Средство для отпугивания насекомых: мазь',
    nameEn: '',
    description: 'Бутыль из тыквы или флакон мази содержит 20 порций мази. Одна порция защищает носителя от обычных насекомых в течение 24 часов. Средство водостойкое, так что оно не смывается дождём.',
    cost: 100,
    source: 'ToA:32',
    category: 'Товары',
  },
  {
    id: 'sredstvo dlia otpugivaniia nasekomy`kh: aromaticheskaia svecha',
    name: 'Средство для отпугивания насекомых: ароматическая свеча',
    nameEn: '',
    description: 'Свеча горит в течение 8 часов и отгоняет насекомых в радиусе 20 фт вокруг себя.',
    cost: 10,
    source: 'ToA:32',
    category: 'Товары',
  },
  {
    id: 'dozhdesbornik',
    name: 'Дождесборник',
    nameEn: '',
    description: 'Простое устройство, состоящее из квадратного куска шкуры со стороной 5 фт и деревянного каркаса с ножками. Будучи растянутой на каркасе, шкура формирует бассейн, который может собрать два галлона питьевой воды за дюйм осадков и вмещает до 8 галлонов воды. Шкура и каркас складываются и удобны в транспортировке.',
    cost: 100,
    weight: 5,
    source: 'ToA:32',
    category: 'Товары',
  },
  {
    id: 'vino, oby`chnoe',
    name: 'Вино, обычное',
    nameEn: '',
    description: 'кружка',
    cost: 20,
    source: 'PHB:158',
    category: 'Еда и напитки',
  },
  {
    id: 'tezh: kruzhka',
    name: 'Теж: кружка',
    nameEn: 'Tej',
    description: 'Перебродивший напиток янтарного цвета на основе мёда. В Чульте он куда более распространён и популярен, чем пиво или эль.',
    cost: 4,
    source: 'ToA:32',
    category: 'Еда и напитки',
  },
  {
    id: 'tezh: bochonok v 1 gallon',
    name: 'Теж: бочонок в 1 галлон',
    nameEn: 'Tej',
    description: 'Перебродивший напиток янтарного цвета на основе мёда. В Чульте он куда более распространён и популярен, чем пиво или эль.',
    cost: 20,
    source: 'ToA:32',
    category: 'Еда и напитки',
  },
  {
    id: 'vino, oby`chnoe',
    name: 'Вино, обычное',
    nameEn: '',
    description: 'бутылка',
    cost: 50,
    source: 'PHB:158',
    category: 'Еда и напитки',
  },
  {
    id: 'vino, otlichnoe',
    name: 'Вино, отличное',
    nameEn: '',
    description: 'кружка',
    cost: 400,
    source: 'PHB:158',
    category: 'Еда и напитки',
  },
  {
    id: 'vino, otlichnoe',
    name: 'Вино, отличное',
    nameEn: '',
    description: 'бутылка',
    cost: 1000,
    source: 'PHB:158',
    category: 'Еда и напитки',
  },
  {
    id: 'miaso',
    name: 'Мясо',
    nameEn: '',
    description: 'кусок',
    cost: 300,
    source: 'PHB:158',
    category: 'Еда и напитки',
  },
  {
    id: 'pivo',
    name: 'Пиво',
    nameEn: '',
    description: 'кружка',
    cost: 4,
    source: 'PHB:158',
    category: 'Еда и напитки',
  },
  {
    id: 'pivo',
    name: 'Пиво',
    nameEn: '',
    description: 'галлон',
    cost: 20,
    source: 'PHB:158',
    category: 'Еда и напитки',
  },
  {
    id: 'sy`r',
    name: 'Сыр',
    nameEn: '',
    description: 'кусок',
    cost: 10,
    source: 'PHB:158',
    category: 'Еда и напитки',
  },
  {
    id: 'torzhestvenny`i` obed',
    name: 'Торжественный обед',
    nameEn: '',
    description: 'на 1 едока',
    cost: 1000,
    source: 'PHB:158',
    category: 'Еда и напитки',
  },
  {
    id: 'kHleb',
    name: 'Хлеб',
    nameEn: '',
    description: 'ломоть',
    cost: 2,
    source: 'PHB:158',
    category: 'Еда и напитки',
  },
  {
    id: 'krov` assasina',
    name: 'Кровь ассасина',
    nameEn: 'Assassin’s Blood',
    description: `Существо, подвергшееся действию этого яда, должно совершить спасбросок Телосложения со Сл 10. При провале оно получает урон ядом 6 (1к12) и становится отравленным на 24 часа. При успехе существо получает половину урона и не становится отравленным.`,
    damage: {
      cubeType: 12,
      cubeCount: 1,
    },
    saveThrow: {
      type: 'con',
      dc: 10,
    },
    cost: 15000,
    damageType: 'poison',
    poisonType: 'ingested',
    source: 'DMG 257',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'dy`m zhzhyonnogo otura',
    name: 'Дым жжённого отура',
    nameEn: 'Burnt Othur Fumes',
    description: `Существо, подвергшееся действию этого яда, должно преуспеть в спасброске Телосложения со Сл 13, иначе оно получит урон ядом 10 (3к6) и будет должно повторять этот спасбросок в начале каждого своего хода. При каждом провале персонаж получит урон ядом 3 (1к6). После трёх успехов яд прекратит своё действие.`,
    damage: {
      cubeType: 6,
      cubeCount: 3,
    },
    saveThrow: {
      type: 'con',
      dc: 13,
    },
    cost: 50000,
    damageType: 'poison',
    poisonType: 'inhaled',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'sliz` polzaiushchego padal`shchika',
    name: 'Слизь ползающего падальщика',
    nameEn: 'Crawler Mucus',
    description: `Этот яд собирают с мёртвого или недееспособного ползающего падальщика. Существо, подвергшееся действию этого яда, должно преуспеть в спасброске Телосложения со Сл 13, иначе оно станет отравленным на 1 минуту. Будучи отравленным, существо также парализовано. Существо может повторять спасбросок в конце каждого своего хода, оканчивая эффект на себе при успехе.`,
    saveThrow: {
      type: 'con',
      dc: 13,
    },
    cost: 20000,
    poisonType: 'contact',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'iad drou',
    name: 'Яд дроу',
    nameEn: 'Drow Poison',
    description: `Обычно этот яд изготавливают только дроу, к тому же в местах, где нет солнечного света. Существо, подвергшееся действию этого яда, должно преуспеть в спасброске Телосложения со Сл 13, иначе оно станет отравленным на 1 час. Если спасбросок провален на 5 или больше единиц, существо также лишено сознания, пока отравлено. Существо приходит в сознание, если получает урон или другое существо действием его потрясёт, чтобы разбудить.`,
    saveThrow: {
      type: 'con',
      dc: 13,
    },
    cost: 20000,
    poisonType: 'injury',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'e`ssentciia e`fira',
    name: 'Эссенция эфира',
    nameEn: 'Essence of Ether',
    description: `Существо, подвергшееся действию этого яда, должно преуспеть в спасброске Телосложения со Сл 15, иначе оно станет отравленным на 8 часов. Существо также лишено сознания, пока отравлено. Существо приходит в сознание, если получает урон или другое существо действием его потрясёт, чтобы разбудить.`,
    saveThrow: {
      type: 'con',
      dc: 15,
    },
    cost: 30000,
    poisonType: 'inhaled',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'zloba',
    name: 'Злоба',
    nameEn: 'Malice',
    description: `Существо, подвергшееся действию этого яда, должно преуспеть в спасброске Телосложения со Сл 15, иначе оно станет отравленным на 1 час. Существо ослеплено, пока отравлено.`,
    saveThrow: {
      type: 'con',
      dc: 15,
    },
    cost: 25000,
    poisonType: 'inhaled',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'polunochny`e slyozy',
    name: 'Полуночные слёзы',
    nameEn: 'Midnight Tears',
    description: `Существо, проглотившее этот яд, до полуночи ни от чего не страдает. Если до этого момента яд не был нейтрализован, существо должно преуспеть в спасброске Телосложения со Сл 17, получая урон ядом 31 (9к6) при провале или половину этого урона при успехе.`,
    damage: {
      cubeType: 6,
      cubeCount: 9,
    },
    saveThrow: {
      type: 'con',
      dc: 17,
    },
    cost: 150000,
    damageType: 'poison',
    poisonType: 'ingested',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'maslo taggita',
    name: 'Масло таггита',
    nameEn: 'Oil of Taggit',
    description: `Существо, подвергшееся действию этого яда, должно преуспеть в спасброске Телосложения со Сл 13, иначе оно станет отравленным на 24 часа. Существо также лишено сознания, пока отравлено. Существо приходит в сознание, если получает урон.`,
    saveThrow: {
      type: 'con',
      dc: 13,
    },
    cost: 40000,
    poisonType: 'contact',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'blednaia nastoi`ka',
    name: 'Бледная настойка',
    nameEn: 'Pale Tincture',
    description: `Существо, подвергшееся действию этого яда, должно преуспеть в спасброске Телосложения со Сл 16, иначе получит урон ядом 3 (1к6) и станет отравленным. Отравленное существо должно повторять спасбросок каждые 24 часа, получая урон ядом 3 (1к6) при провале. Пока яд действует, урон, причинённый им, ничем не может быть вылечен. После семи успешных спасбросков эффект оканчивается, и существо может лечиться как обычно.`,
    damage: {
      cubeType: 6,
      cubeCount: 1,
    },
    saveThrow: {
      type: 'con',
      dc: 16,
    },
    cost: 25000,
    damageType: 'poison',
    poisonType: 'ingested',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'iad lilovogo chervia',
    name: 'Яд лилового червя',
    nameEn: 'Purple Worm Poison',
    description: `Этот яд собирают с мёртвого или недееспособного лилового червя. Существо, подвергшееся действию этого яда, должно совершить спасбросок Телосложения со Сл 19, получая при провале урон ядом 42 (12к6), или половину этого урона при успехе.`,
    damage: {
      cubeType: 6,
      cubeCount: 12,
    },
    saveThrow: {
      type: 'con',
      dc: 19,
    },
    cost: 200000,
    damageType: 'poison',
    poisonType: 'injury',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'zmeiny`i` iad',
    name: 'Змеиный яд',
    nameEn: 'Serpent Venom',
    description: `Этот яд собирают с мёртвой или недееспособной гигантской ядовитой змеи. Существо, подвергшееся действию этого яда, должно преуспеть в спасброске Телосложения со Сл 11, получая урон ядом 10 (3к6) при провале, или половину этого урона при успехе.`,
    damage: {
      cubeType: 6,
      cubeCount: 3,
    },
    saveThrow: {
      type: 'con',
      dc: 11,
    },
    cost: 20000,
    damageType: 'poison',
    poisonType: 'injury',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'stupor',
    name: 'Ступор',
    nameEn: 'Torpor',
    description: `Существо, подвергшееся действию этого яда, должно преуспеть в спасброске Телосложения со Сл 15, иначе оно станет отравленным на 4к6 часов. Существо также недееспособно, пока отравлено.`,
    saveThrow: {
      type: 'con',
      dc: 15,
    },
    cost: 60000,
    poisonType: 'ingested',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'sy`vorotka pravdy',
    name: 'Сыворотка правды',
    nameEn: 'Truth Serum',
    description: `Существо, подвергшееся действию этого яда, должно преуспеть в спасброске Телосложения со Сл 11, иначе станет отравленным на 1 час. Пока существо отравлено, оно не может сознательно говорить ложь, как если бы оно находилось под действием заклинания «Область истины».`,
    saveThrow: {
      type: 'con',
      dc: 11,
    },
    cost: 15000,
    poisonType: 'ingested',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
  {
    id: 'iad viverny',
    name: 'Яд виверны',
    nameEn: 'Wyvern Poison',
    description: `Этот яд собирают с мёртвой или недееспособной виверны. Существо, подвергшееся действию этого яда, должно совершить спасбросок Телосложения со Сл 15, получая при провале урон ядом 24 (7к6) или половину этого урона при успехе.`,
    damage: {
      cubeType: 6,
      cubeCount: 7,
    },
    saveThrow: {
      type: 'con',
      dc: 15,
    },
    cost: 120000,
    damageType: 'poison',
    poisonType: 'injury',
    source: 'DMG:258',
    category: 'Снаряжение',
    subcategory: 'Яды',
  },
]

const itemListPreparedForFullTextSearch = _.sortBy(
  dndItemList.map(
    item => ({
      ...item,
      [SEARCH_PROP_NAME]: [
        item.name,
        item.nameEn,
        item.description,
        item.category,
        item.subcategory,
      ]
        .filter(
          e => e,
        )
        .map(
          e => String(e).toLowerCase(),
        )
        .join(' '),
    }),
  ),
  [
    'name',
    'description',
  ],
)

export default itemListPreparedForFullTextSearch

export const dndItemCollection = listToCollectionById(dndItemList)

