import {LOOT_TYPE_ART, LOOT_TYPE_TRINKET, LOOT_TYPE_GEM} from '@/constants/dnd/dndLootTypeList'

export default [
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Азурит`,
    description: `непрозрачный, пёстрый тёмно-синий`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Бирюза`,
    description: `непрозрачная, зелёно-голубая`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Гематит`,
    description: `непрозрачный, серо-чёрный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 2500,
    type: LOOT_TYPE_ART,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: true,
    name: `Серебряный кувшин`,
    description: ``,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 2500,
    type: LOOT_TYPE_ART,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Резная статуэтка из кости`,
    description: ``,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 2500,
    type: LOOT_TYPE_ART,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Вышитый шёлковый носовой платок`,
    description: ``,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 2500,
    type: LOOT_TYPE_ART,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Маленький золотой браслет`,
    description: ``,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 2500,
    type: LOOT_TYPE_ART,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Одеяние`,
    description: `из золотой парчи`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 2500,
    type: LOOT_TYPE_ART,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Чёрная бархатная маска`,
    description: `вышитая серебряной нитью`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 2500,
    type: LOOT_TYPE_ART,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Медная чаша`,
    description: `с серебряной филигранью`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 2500,
    type: LOOT_TYPE_ART,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Пара гравированных игральных костей`,
    description: ``,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 2500,
    type: LOOT_TYPE_ART,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Небольшое зеркальце`,
    description: `в расписной деревянной раме`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 2500,
    type: LOOT_TYPE_ART,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Золотой медальон`,
    description: `с портретом возлюбленной внутри`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Мумифицированная рука гоблина`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Старая стеклянная шахматная фигура`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 100,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Золотая монета`,
    description: `отчеканенная в неизвестной стране`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Кусочек кристалла`,
    description: `слабо светящийся в лунном свете`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Дневник`,
    description: `написанный на неизвестном вам языке`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 10,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Латунное кольцо`,
    description: `которое не темнеет со временем`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Пара игральных костей`,
    description: `у обеих вместо шестёрок нарисованы черепа`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 10,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Небольшой идол`,
    description: `изображающий страшное чудовище, насылающий кошмары, когда вы спите рядом с ним`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Верёвочное ожерелье`,
    description: `на котором висят четыре мумифицированных эльфийских пальца`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Квитанция для получения посылки`,
    description: `в неизвестном вам королевстве`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `30-граммовый кусочек неизвестного материала`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Маленькая тряпичная кукла`,
    description: `утыканная иголками`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Зуб неизвестного зверя`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Огромная чешуйка`,
    description: `возможно, драконья`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Ярко-зелёное перо`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Старая гадальная карта`,
    description: `с лицом, похожим на ваше`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 5,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Стеклянная сфера`,
    description: `заполненная дымом`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 10,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Полукилограммовое яйцо с ярко-красной скорлупой`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 50,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Курительная трубка`,
    description: `из которой вылетают пузыри`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: true,
    name: `Стеклянный графин с мутной жидкостью`,
    description: `в которой плавает странный кусочек мяса`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Крошечная музыкальная шкатулка гномьей работы`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 10,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Маленькая деревянная статуэтка нарядного полурослика`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Латунная сфера`,
    description: `покрытая странными рунами`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Разноцветный каменный диск`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 50,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Крошечный серебряный ворон`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Сумка`,
    description: `в которой лежат 47 человеческих зубов. Один с кариесом.`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Кусок обсидиана`,
    description: `всегда тёплый на ощупь`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 10,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Коготь дракона`,
    description: `подвешенный на простом кожаном шнурке`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Пара старых носков`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Чистая книга`,
    description: `на страницах которой не получается писать ни чернилами, ни мелом, ни углём, и никакими другими обычным средствами`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 50,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Серебряный значок`,
    description: `в форме пятиконечной звезды`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 5,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Кривой ножик`,
    description: ``,
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Стеклянный флакон`,
    description: `с обрезками ногтей`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 100,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Прямоугольное металлическое устройство`,
    description: `с двумя крошечными металлическими колпачками на одной стороне. Если его намочить, оно сыпет искры`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Белые перчатки с блёстками`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Одеяние с сотней крохотных карманов`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Маленький каменный кирпич`,
    description: `который ничего не весит`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Крохотный набросок портрета гоблина`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 50,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Пустой флакон`,
    description: `пахнущий духами при открытии`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Драгоценный камень`,
    description: `который всем кроме вас кажется куском угля`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Кусок старого знамени`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Знак различия древнего легиона`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 3,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Крохотный серебряный колокольчик`,
    description: `без язычка`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 200,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Механическая канарейка в гномьей лампе`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 50,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Крохотный сундук`,
    description: `вырезанный так, что кажется, что у него невероятно глубокое дно`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 100,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Мёртвый спрайт в чистой стеклянной бутылке`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Запаянная металлическая банка`,
    description: `в которой, судя по звукам, находится жидкость`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Запаянная металлическая банка`,
    description: `в которой, судя по звукам, находится песок`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Запаянная металлическая банка`,
    description: `в которой, судя по звукам, находятся пауки`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Запаянная металлическая банка`,
    description: `в которой, судя по звукам, находится битое стекло`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 2000,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: false,
    isOnlyLargeCreatureItem: false,
    name: `Стеклянная сфера с водой`,
    description: `в которой плавает механическая золотая рыбка`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 100,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Серебряная ложка`,
    description: `с выгравированной на ручке буквой «М»`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 50,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Свисток из дерева`,
    description: `золотого цвета`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Мёртвый скарабей`,
    description: `размером с ладонь`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Два игрушечных солдатика`,
    description: `один — без головы`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Небольшая коробка с пуговицами разного размера`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Свеча`,
    description: `которая никак не загорается`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Крохотная клетка`,
    description: `без дверцы`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Старый ключ`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Не поддающаяся расшифровке карта сокровищ`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Рукоятка от сломанного меча`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: false,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Кроличья лапка`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 101,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Стеклянный глаз`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Камея с резным портретом ужасного лица`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 20,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Серебряный череп размером с монету`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 100,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Алебастровая маска`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 10,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Пирамидка клейкого чёрного дурно пахнущего благовония`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Ночной колпак, дарующий приятные сны`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Один костяной калтроп`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Золотая оправа монокля без линзы`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 10,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Кубик с длиной ребра 2 сантиметра`,
    description: `все стороны раскрашены в разные цвета`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Хрустальная дверная ручка`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Пакетик розовой пыли`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Два листа пергамента с фрагментом нот прекрасной песни`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Серебряная серьга в виде слезинки`,
    description: `сделанная из настоящей слезинки`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Яичная скорлупа`,
    description: `разрисованная с жуткими подробностями сценами человеческих мук`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 100,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Веер`,
    description: `на котором в раскрытом состоянии видно спящую кошку`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Набор костяных трубочек`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Четырёхлистный клевер`,
    description: `засушенный в книге о манерах и этикете`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Лист пергамента`,
    description: `на котором изображена сложная механическая конструкция`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 100,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Разукрашенные ножны`,
    description: `под которые вы никак не можете найти подходящий клинок`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Приглашение на вечеринку`,
    description: `на которой произошло убийство`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Бронзовая пентаграмма`,
    description: `с выгравированной в центре крысиной головой`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Фиолетовый носовой платок`,
    description: `с вышитым именем великого архимага`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Половинка плана храма`,
    description: `замка или другого строения`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Кусочек сложенной ткани`,
    description: `который, если развернуть, превращается в модную кепку`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Квитанция о депозите в банке далёкого города`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Дневник`,
    description: `в котором не хватает семь страниц`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 100,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Пустая серебряная табакерка`,
    description: `с надписью на поверхности «грёзы»`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Железный святой символ неизвестного божества`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Книга о восхождении и свержении легендарного героя`,
    description: `в которой нет последней главы`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Сосуд с драконьей кровью`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Древняя эльфийская стрела`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Иголка`,
    description: `которая никогда не гнётся`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Красивая дварфская брошь`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Пустая бутылка из-под вина с небольшой наклейкой`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `«Винокурня Винного Волшебника, Красное драконье, 331422-В»`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 10,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Плитка мозаики с разноцветной глазированной поверхностью`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Окаменевшая мышь`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Чёрный пиратский флаг`,
    description: `с черепом и костями дракона`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Крохотный металлический краб`,
    description: `который двигается, когда на него не смотрят`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Крохотный металлический паук`,
    description: `который двигается, когда на него не смотрят`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Стеклянная бутылка сала с этикеткой «Жир грифона»`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Деревянная коробка с керамическим дном`,
    description: `в которой живёт червяк с двумя головами на каждом конце тела`,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 100,
    type: LOOT_TYPE_TRINKET,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Металлическая урна с прахом героя`,
    description: ``,
    source: {
      id: 'PHB',
      page: 161,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Глазчатый агат`,
    description: `полупрозрачный, чередующиеся круги серого и зелёного цвета`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Глазчатый агат`,
    description: `полупрозрачный, чередующиеся круги серого и белого цвета`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Глазчатый агат`,
    description: `полупрозрачный, чередующиеся круги серого и коричневого цвета`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Глазчатый агат`,
    description: `полупрозрачный, чередующиеся круги серого и голубого цвета`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Глазчатый агат`,
    description: `полупрозрачный, чередующиеся круги белого и коричневого цвета`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Глазчатый агат`,
    description: `полупрозрачный, чередующиеся круги белого и голубого цвета`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Глазчатый агат`,
    description: `полупрозрачный, чередующиеся круги белого и зелёного цвета`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Глазчатый агат`,
    description: `полупрозрачный, чередующиеся круги коричневого и голубого цвета`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Глазчатый агат`,
    description: `полупрозрачный, чередующиеся круги коричневого и зелёного цвета`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Глазчатый агат`,
    description: `полупрозрачный, чередующиеся круги голубого и зелёного цвета`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Голубой кварц`,
    description: `прозрачный, голубой`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Лазурит`,
    description: `непрозрачный, голубой и синий с жёлтыми вкраплениями`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Малахит`,
    description: `непрозрачный, с чередующимися светло- и тёмно-зелёными полосами`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Моховой агат`,
    description: `полупрозрачный, розовый или бело- жёлтый с мшистыми серыми пятнами`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Моховой агат`,
    description: `полупрозрачный, розовый или бело- жёлтый с мшистыми зелёными пятнами`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Обсидиан`,
    description: `непрозрачный, чёрный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Полосчатый агат`,
    description: `полупрозрачный, с чередующимися коричневыми и красными полосами`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Полосчатый агат`,
    description: `полупрозрачный, с чередующимися коричневыми и белыми полосами`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Полосчатый агат`,
    description: `полупрозрачный, с чередующимися коричневыми и голубыми полосами`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Полосчатый агат`,
    description: `полупрозрачный, с чередующимися голубыми и белыми полосами`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Полосчатый агат`,
    description: `полупрозрачный, с чередующимися голубыми и красными полосами`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Полосчатый агат`,
    description: `полупрозрачный, с чередующимися белыми и красными полосами`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Родохрозит`,
    description: `непрозрачный, светло-розовый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 1000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Тигровый глаз`,
    description: `полупрозрачный, коричневый с золотой серединкой`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Гелиотроп`,
    description: `непрозрачный, тёмно-серый с красными вкраплениями`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Звёздчатый розовый кварц`,
    description: `полупрозрачный, розовый камень с белой звездой по центру`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Кварц`,
    description: `прозрачный, белый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Кварц`,
    description: `прозрачный, дымчатый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Кварц`,
    description: `прозрачный, жёлтый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Лунный камень`,
    description: `полупрозрачный, белый с бледно-голубым отливом`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Оникс`,
    description: `непрозрачный, чёрно-белые полосы`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Оникс`,
    description: `непрозрачный, чисто чёрный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Оникс`,
    description: `непрозрачный, чисто белый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Сардоникс`,
    description: `непрозрачный, бело-красные полосы`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Сердолик`,
    description: `непрозрачный, оранжевый с переходом в красно-коричневый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Халцедон`,
    description: `непрозрачный, белый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Хризопраз`,
    description: `полупрозрачный, зелёный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Циркон`,
    description: `прозрачный, бледный зелёно-голубой`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Цитрин`,
    description: `прозрачный, жёлто-коричневый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Яшма`,
    description: `непрозрачная, синяя`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Яшма`,
    description: `непрозрачная, чёрная`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 5000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Яшма`,
    description: `непрозрачная, коричневая`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Аметист`,
    description: `прозрачный, тёмно-фиолетовый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Гагат`,
    description: `непрозрачный, чёрный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Гранат`,
    description: `прозрачный, красный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Гранат`,
    description: `прозрачный, зелёно-коричневый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Гранат`,
    description: `прозрачный, фиолетовый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Жемчуг`,
    description: `непрозрачный, переливчатый белый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Жемчуг`,
    description: `непрозрачный, переливчатый жёлтый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Жемчуг`,
    description: `непрозрачный, переливчатый розовый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Коралл`,
    description: `непрозрачный, тёмно-красный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Нефрит`,
    description: `полупрозрачный, светло-зелёный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Нефрит`,
    description: `полупрозрачный, тёмно-зелёный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Нефрит`,
    description: `полупрозрачный, белый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Турмалин`,
    description: `прозрачный, красный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Турмалин`,
    description: `прозрачный, бледно-зелёный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Турмалин`,
    description: `прозрачный, синий`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Турмалин`,
    description: `прозрачный, коричневый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Хризоберилл`,
    description: `прозрачный, жёлто-зелёный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Хризоберилл`,
    description: `прозрачный, светло-зелёный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Шпинель`,
    description: `прозрачная, красная`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Шпинель`,
    description: `прозрачная, красно-коричневая`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Шпинель`,
    description: `прозрачная, тёмно-зелёная`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 10000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Янтарь`,
    description: `прозрачный, жёлто-золотой`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 50000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Аквамарин`,
    description: `прозрачный, зелёно-голубой`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 50000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Александрит`,
    description: `прозрачный, тёмно-зелёный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 50000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Синяя шпинель`,
    description: `прозрачная, синяя`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 50000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Топаз`,
    description: `прозрачный, золотисто-жёлтый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 50000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Хризолит`,
    description: `прозрачный, сочный оливково-зелёный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 50000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Чёрный жемчуг`,
    description: `непрозрачный, чисто чёрный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 100000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Голубой сапфир`,
    description: `прозрачный, бело-голубой`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 100000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Голубой сапфир`,
    description: `прозрачный, голубой`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 100000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Голубой сапфир`,
    description: `прозрачный, умеренно синий`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 100000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Жёлтый сапфир`,
    description: `прозрачный, огненно-жёлтый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 100000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Жёлтый сапфир`,
    description: `прозрачный, жёлто-зелёный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 100000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Звёздчатый рубин`,
    description: `полупрозрачный, рубин с белёсой звездой в центре`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 100000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Звёздчатый сапфир`,
    description: `полупрозрачный, синий сапфир с белёсой звездой в центре`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 100000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Изумруд`,
    description: `прозрачный, насыщенный ярко-зелёный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 100000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Огненный опал`,
    description: `полупрозрачный, огненно-красный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 100000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Опал`,
    description: `полупрозрачный, голубой с зелёными и золотыми вкраплениями`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 100000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Чёрный опал`,
    description: `полупрозрачный, тёмно-зелёный с чёрными пятнышками и золотыми вкраплениями`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 500000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Алмаз`,
    description: `прозрачный`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 500000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Алмаз`,
    description: `сине-белый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 500000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Алмаз`,
    description: `ярко-жёлтый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 500000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Алмаз`,
    description: `розовый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 500000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Алмаз`,
    description: `коричневый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 500000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Алмаз`,
    description: `синий`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 500000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Гиацинт`,
    description: `прозрачный, огненно-оранжевый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 500000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Рубин`,
    description: `прозрачный, чисто красный с переходом в тёмно-алый`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
  {
    cost: 500000,
    type: LOOT_TYPE_GEM,
    isCleverItem: true,
    isDumbItem: true,
    isOnlyLargeCreatureItem: false,
    name: `Чёрный сапфир`,
    description: `полупрозрачный, блестящий чёрный с яркими вкраплениями`,
    source: {
      id: 'DMG',
      page: 135,
    },
  },
]
