export default (diceResult) => {
  switch (diceResult) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
    case 50:
      return 'nothing'
    case 51:
    case 52:
      return 'map'
    case 53:
    case 54:
      return 'gems'
    case 55:
    case 56:
      return 'ring'
    case 57:
    case 58:
      return 'flacon'
    case 59:
    case 60:
      return 'rotten_quiver'
    case 61:
    case 62:
      return 'gold_piece'
    case 63:
    case 64:
      return 'snake_poison'
    case 65:
    case 66:
      return 'smoke_pipe'
    case 67:
    case 68:
      return 'antisect'
    case 69:
    case 70:
      return 'yepteka'
    case 71:
    case 72:
      return 'potion_animal_friendship'
    case 73:
    case 74:
      return 'potion_survival'
    case 75:
    case 76:
      return 'spell_scroll'
    case 77:
    case 78:
      return 'wywern_poison'
    case 79:
    case 80:
      return 'obsidian_knife'
    case 81:
    case 82:
      return 'pipe_with_gems'
    case 83:
    case 84:
      return 'onyx_stone'
    case 85:
    case 86:
      return 'batiri_mask'
    case 87:
    case 88:
      return 'spyglass'
    case 89:
    case 90:
      return 'lute'
    case 91:
    case 92:
      return 'tools_thief'
    case 93:
    case 94:
      return 'lock'
    case 95:
    case 96:
      return 'Keoghtom'
    case 97:
    case 98:
      return 'horn_of_blasting'
    case 99:
    case 0:
      return 'wand_of_secrets'
  }
}
